import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { CODEX_AGENT } from '../../shared/types/agentWire.ts';
import {
  type CodexConnectFactory,
  type CodexConnectionCore,
  createCodexConnection,
} from '../codexConnection.ts';
import type { CodexEntryResolution, CodexLaunchPlan } from '../codexNodeEntry.ts';
import {
  buildInitializeParams,
  buildThreadStartParams,
  buildTurnInterruptParams,
  buildTurnStartParams,
  CODEX_CLIENT_NAME,
  CODEX_CLIENT_TITLE,
  CODEX_PERMISSION_DEFAULT,
  CodexRuntime,
  type CodexRuntimeOptions,
  compareSandboxEcho,
} from '../codexRuntime.ts';
import { JSONRPC_METHOD_NOT_FOUND } from '../codexWire.ts';
import { SessionRegistry } from '../sessionRegistry.ts';

/**
 * S3 slices 2a + 2c — the Codex runtime shell and its turn loop.
 *
 * The gate item lives in the first describe: the posture that reaches
 * `thread/start` and the posture `session.created` advertises are compared TO
 * EACH OTHER, never to a literal (paradigm from
 * `claudeRuntimeOptions.test.ts:151-219`). A literal on both sides passes while
 * the two drift apart; comparing the captures cannot.
 *
 * The 2c half is verified by replaying the one complete recorded turn we own
 * (`fixtures/codex/codex-filechange-approval-turn.jsonl`, 19 frames) through the
 * REAL connection core, so what is asserted is the wiring that ships: which
 * frames we write, in what order, and which events come out. The failures that
 * matter in a turn loop are ordering and ownership failures, and no amount of
 * isolated unit tests catches those.
 *
 * Everything runs against an in-memory transport driving the real
 * `createCodexConnection` core, so no process is spawned and no quota is spent.
 */

const HOME_DIR = '/tmp/aiclient-codex-home';

const FIXTURES = path.resolve(import.meta.dirname, 'fixtures', 'codex');

interface TurnSchemaShape {
  required: string[];
  propertyNames: string[];
}

/**
 * The binary's own JSON Schema for the turn methods, generated by
 * `codex app-server generate-json-schema` — same provenance as
 * `codex-method-contract.json`, which pins the method NAMES. This one pins the
 * PARAM SHAPES, so a dropped required field (an interrupt missing `turnId`
 * silently interrupts nothing) fails here instead of at runtime.
 */
const turnSchema = JSON.parse(
  readFileSync(path.join(FIXTURES, 'codex-turn-schema.json'), 'utf8')
) as {
  TurnStartParams: TurnSchemaShape;
  TurnInterruptParams: TurnSchemaShape;
  UserInputText: TurnSchemaShape;
  TurnStatus: string[];
};

interface FixtureEnvelope {
  dir: string;
  tMs: number | null;
  raw: { method?: string; params?: Record<string, unknown>; id?: number };
}

/** The recorded turn, `<-` frames only, in capture order. */
function loadTurnFixture(file: string): FixtureEnvelope[] {
  return readFileSync(path.join(FIXTURES, file), 'utf8')
    .split('\n')
    .filter((line) => line.trim().length > 0)
    .map((line) => JSON.parse(line) as FixtureEnvelope)
    .filter((frame) => frame.dir === '<-' && frame.raw.method !== undefined);
}

/** The thread the recorded turn belongs to — every frame in it carries this id. */
const FIXTURE_THREAD = '019fd82d-ae7f-7b91-955b-0b1d5b5af4e2';
const FIXTURE_TURN = '019fd82d-aeb2-7f32-8eed-509fc131fc86';
const FIXTURE_ITEM = 'exec-f5ec3f09-0b15-4ba7-ab1b-13bcfaa79ccf';
const APPROVAL_METHOD = 'item/fileChange/requestApproval';
/**
 * The approval frame in the fixture was reassembled from a `method` + `params`
 * pair, so it carries no JSON-RPC `id` (the manifest says so, and forbids
 * "completing" the file). `0` is not invented here either: the same turn's
 * `serverRequest/resolved {requestId: 0}` names it. The id is therefore added
 * BY THE TEST, at replay time, and the fixture stays untouched.
 */
const APPROVAL_ID = 0;

const PLAN: CodexLaunchPlan = {
  nodeExecPath: '/opt/node24/bin/node',
  codexJsPath: '/opt/codex/lib/node_modules/@openai/codex/bin/codex.js',
  args: ['/opt/codex/lib/node_modules/@openai/codex/bin/codex.js', 'app-server'],
  source: 'node_sibling',
};

/**
 * CONSTRUCTED, not recorded: the only real echo we hold is the read-only one in
 * `fixtures/codex/codex-thread-start-echo.partial.json`. The camel-case spelling
 * here is a plausible shape used to exercise the comparison, and the test that
 * asserts a `match` against REAL bytes uses that fixture's values instead.
 */
const THREAD_START_RESULT = {
  threadId: 'thr-0001',
  approvalPolicy: 'on-request',
  sandbox: { type: 'workspaceWrite', networkAccess: false },
};

interface OutboundFrame {
  id?: number;
  method?: string;
  params?: Record<string, unknown>;
  result?: unknown;
}

interface Harness {
  runtime: CodexRuntime;
  registry: SessionRegistry;
  events: Array<Record<string, unknown>>;
  logs: string[];
  /** Ordered transport transcript: `write:<method>` / `reply:<id>` / `kill:<reason>`. */
  ops: string[];
  connectInputs: Array<Parameters<CodexConnectFactory>[0]>;
  /** Our outbound requests, parsed. */
  requestFor(method: string): OutboundFrame;
  /** Every outbound frame for a method — a second turn writes a second turn/start. */
  requestsFor(method: string): OutboundFrame[];
  replies(): OutboundFrame[];
  event(type: string): Record<string, unknown> | undefined;
  eventsOf(type: string): Array<Record<string, unknown>>;
  /** Feed one inbound frame from "codex". */
  push(frame: Record<string, unknown>): void;
  /** Kill the "process" the way a crash would — through the real connection core. */
  exit(info: { code: number | null; signal: string | null }): void;
  waitFor(check: () => boolean, what: string): Promise<void>;
  waitForEvent(type: string): Promise<Record<string, unknown>>;
}

function makeHarness(
  options: {
    threadStartResult?: unknown;
    threadStartError?: { code: number; message: string };
    /** `false` = codex never answers `turn/start`, so the turn id stays unknown. */
    answerTurnStart?: boolean;
    turnStartResult?: unknown;
    turnStartError?: { code: number; message: string };
    resolveLaunch?: () => CodexEntryResolution;
    ensureHome?: CodexRuntimeOptions['ensureHome'];
    appVersion?: string;
    codexHomeDir?: string;
  } = {}
): Harness {
  const events: Array<Record<string, unknown>> = [];
  const logs: string[] = [];
  const ops: string[] = [];
  const written: OutboundFrame[] = [];
  const connectInputs: Array<Parameters<CodexConnectFactory>[0]> = [];
  let core: CodexConnectionCore | null = null;

  function answer(frame: OutboundFrame): void {
    if (!core || frame.id === undefined) return;
    if (frame.method === 'initialize') {
      core.pushStdout(`${JSON.stringify({ id: frame.id, result: { codexHome: HOME_DIR } })}\n`);
      return;
    }
    if (frame.method === 'thread/start') {
      const body = options.threadStartError
        ? { id: frame.id, error: options.threadStartError }
        : { id: frame.id, result: options.threadStartResult ?? THREAD_START_RESULT };
      core.pushStdout(`${JSON.stringify(body)}\n`);
      return;
    }
    if (frame.method === 'turn/start') {
      // Silence is a real posture, not a broken fake: whether codex answers
      // `turn/start` at turn START or at turn END is [未测], so the turn loop has
      // to work with the id it has not been told yet.
      if (options.answerTurnStart === false) return;
      const body = options.turnStartError
        ? { id: frame.id, error: options.turnStartError }
        : {
            id: frame.id,
            // `TurnStartResponse` = `{turn: Turn}`, `Turn` requires id/items/status
            // [实测 codex-turn-schema.json].
            result: options.turnStartResult ?? {
              turn: { id: FIXTURE_TURN, items: [], status: 'inProgress' },
            },
          };
      core.pushStdout(`${JSON.stringify(body)}\n`);
      return;
    }
    if (frame.method === 'turn/interrupt') {
      // `TurnInterruptResponse` is an empty object [实测 schema].
      core.pushStdout(`${JSON.stringify({ id: frame.id, result: {} })}\n`);
    }
  }

  const connect: CodexConnectFactory = (input) => {
    connectInputs.push(input);
    const created = createCodexConnection({
      transport: {
        pid: 4242,
        write: (line) => {
          const frame = JSON.parse(line) as OutboundFrame;
          written.push(frame);
          ops.push(frame.method ? `write:${frame.method}` : `reply:${String(frame.id)}`);
          // A real process never answers inside the write call; a microtask
          // keeps the ordering realistic without a timer.
          if (frame.method !== undefined && frame.id !== undefined)
            queueMicrotask(() => answer(frame));
        },
        kill: (reason) => ops.push(`kill:${reason}`),
      },
      handlers: input.handlers,
      log: (...args) =>
        logs.push(args.map((a) => (typeof a === 'string' ? a : JSON.stringify(a))).join(' ')),
    });
    core = created;
    return created.connection;
  };

  const registry = new SessionRegistry();
  const runtime = new CodexRuntime({
    emit: (event) => events.push(event),
    log: (...args) =>
      logs.push(args.map((a) => (typeof a === 'string' ? a : JSON.stringify(a))).join(' ')),
    registry,
    codexHomeDir: options.codexHomeDir ?? HOME_DIR,
    appVersion: options.appVersion ?? '9.9.9-test',
    connect,
    resolveLaunch: options.resolveLaunch ?? (() => ({ ok: true, plan: PLAN })),
    ensureHome:
      options.ensureHome ??
      ((input) => ({
        homeDir: input.homeDir,
        projection: { toml: '', kept: [], dropped: [] },
        authCopied: false,
      })),
  });

  const harness: Harness = {
    runtime,
    registry,
    events,
    logs,
    ops,
    connectInputs,
    requestFor: (method) => {
      const frame = written.find((f) => f.method === method);
      if (!frame) throw new Error(`no outbound request for ${method}; saw ${ops.join(', ')}`);
      return frame;
    },
    requestsFor: (method) => written.filter((f) => f.method === method),
    replies: () => written.filter((f) => f.method === undefined),
    event: (type) => events.find((e) => e.type === type),
    eventsOf: (type) => events.filter((e) => e.type === type),
    push: (frame) => core?.pushStdout(`${JSON.stringify(frame)}\n`),
    exit: (info) => core?.handleExit(info),
    waitFor: async (check, what) => {
      for (let i = 0; i < 200; i += 1) {
        if (check()) return;
        await new Promise((resolve) => setTimeout(resolve, 2));
      }
      throw new Error(`timed out waiting for ${what}`);
    },
    waitForEvent: async (type) => {
      await harness.waitFor(() => events.some((e) => e.type === type), `event ${type}`);
      return events.find((e) => e.type === type) as Record<string, unknown>;
    },
  };
  return harness;
}

type Payload = Record<string, unknown>;

function payload(event: Record<string, unknown> | undefined): Payload {
  return (event?.payload ?? {}) as Payload;
}

async function startedSession(sessionId = 's1'): Promise<Harness> {
  const h = makeHarness();
  h.runtime.createSession({ sessionId, workspacePath: '/work/repo', requestId: 'req-create' });
  await h.waitForEvent('session.created');
  return h;
}

/**
 * A session bound to the RECORDED thread id, so the fixture's frames are not
 * dropped as foreign (`thread/start` normally hands back this harness's own
 * `thr-0001`, and the per-turn normalizer is pinned to whatever it returned).
 */
async function turnSession(
  options: Parameters<typeof makeHarness>[0] = {},
  sessionId = 's1'
): Promise<Harness> {
  const h = makeHarness({
    threadStartResult: {
      threadId: FIXTURE_THREAD,
      approvalPolicy: 'on-request',
      sandbox: { type: 'workspaceWrite', networkAccess: false },
    },
    ...options,
  });
  h.runtime.createSession({ sessionId, workspacePath: '/work/repo', requestId: 'req-create' });
  await h.waitForEvent('session.created');
  h.events.length = 0;
  return h;
}

/**
 * Rewrite a frame's turn identity, keeping both spellings in step: `turnId` on
 * the item frames and `turn.id` on `turn/completed` [实测].
 */
function retargetTurn(
  params: Record<string, unknown> | undefined,
  turnId: string
): Record<string, unknown> | undefined {
  if (!params) return params;
  const next: Record<string, unknown> = { ...params };
  if (typeof next.turnId === 'string') next.turnId = turnId;
  if (next.turn !== null && typeof next.turn === 'object') {
    next.turn = { ...(next.turn as Record<string, unknown>), id: turnId };
  }
  return next;
}

/**
 * Feed the recorded turn the way the real link delivers it: notifications go
 * down the same stdout path as everything else, and the approval frame is
 * replayed as a genuine JSON-RPC SERVER REQUEST (id + method), because that is
 * what decides whether it reaches the pending table or the normalizer.
 *
 * The window is by FRAME INDEX, so `upTo`/`from` name the same boundary from
 * both sides: `upTo: 10` stops right after the approval request, `from: 10`
 * delivers everything codex had already queued behind it.
 *
 * `turnId` re-stamps the recording so it can stand in for a SECOND turn — codex
 * never reuses a turn id, and replaying the recorded one twice would exercise a
 * collision that cannot happen instead of the isolation that must hold.
 * `drop` removes whole methods, so "no status frame ever arrived" is replayed as
 * a real stream rather than asserted about a stream that never existed.
 */
function replayRecordedTurn(
  h: Harness,
  options: {
    from?: number;
    upTo?: number;
    turnId?: string;
    drop?: readonly string[];
  } = {}
): string[] {
  const { from = 0, upTo = Number.POSITIVE_INFINITY, turnId, drop = [] } = options;
  const routed: string[] = [];
  const frames = loadTurnFixture('codex-filechange-approval-turn.jsonl');
  for (const [index, frame] of frames.entries()) {
    if (index < from || index >= upTo) continue;
    const method = frame.raw.method as string;
    if (drop.includes(method)) continue;
    const params = turnId ? retargetTurn(frame.raw.params, turnId) : frame.raw.params;
    routed.push(method);
    h.push(method === APPROVAL_METHOD ? { id: APPROVAL_ID, method, params } : { method, params });
  }
  return routed;
}

/** The prompt every turn test sends. Distinct enough to spot in a params dump. */
const PROMPT = 'add a retry to the fetch helper';

/**
 * A turn ends exactly once, through exactly one of these. Counting them is how
 * "the renderer was told how the turn ended" and "it was told twice" stay
 * distinguishable — both are failures, in opposite directions.
 */
const TERMINALS: readonly string[] = ['session.completed', 'session.failed', 'session.stopped'];

function typesOf(events: Array<Record<string, unknown>>): string[] {
  return events.map((event) => String(event.type));
}

function terminalsOf(events: Array<Record<string, unknown>>): string[] {
  return typesOf(events).filter((type) => TERMINALS.includes(type));
}

/**
 * A session parked exactly where the recording parks: mid-turn, with the
 * fileChange approval registered and unanswered, which is the state Stop, a
 * crash and Close all have to survive.
 */
async function stoppableTurn(options: Parameters<typeof makeHarness>[0] = {}): Promise<Harness> {
  const h = await turnSession(options);
  await h.runtime.send({ sessionId: 's1', text: PROMPT, requestId: 'req-send' });
  replayRecordedTurn(h, { upTo: 10 });
  return h;
}

describe('codexRuntime — permission posture has a single source (gate item)', () => {
  it('sends thread/start exactly the posture session.created reports', async () => {
    const h = await startedSession();

    const start = h.requestFor('thread/start');
    const created = payload(h.event('session.created'));
    const advertised = created.permissionPolicy as {
      approvalPolicy: string;
      sandboxMode: string;
      agent: string;
    };

    // Two CAPTURES compared to each other. A literal on both sides would pass
    // while the constant that feeds them changed under one of them.
    expect(start.params?.approvalPolicy).toBe(advertised.approvalPolicy);
    expect(start.params?.sandbox).toBe(advertised.sandboxMode);
    expect(advertised.agent).toBe(created.agent);
  });

  it('never puts networkAccess into the request, anywhere in the params', async () => {
    // `thread/start` takes `sandbox` as a STRING; networkAccess exists only in
    // the RESULT. Sending it is the "we configured something we cannot
    // configure" failure — the serialized check also catches it nested inside
    // an object-shaped sandbox somebody added later.
    const h = await startedSession();
    const start = h.requestFor('thread/start');

    expect(start.params).not.toHaveProperty('networkAccess');
    expect(JSON.stringify(start.params)).not.toContain('networkAccess');
    expect(typeof start.params?.sandbox).toBe('string');
  });

  it('reports the same agent on the event and on the registry entry', async () => {
    const h = await startedSession();
    const created = payload(h.event('session.created'));

    expect(created.agent).toBe(h.registry.get('s1')?.agent);
    expect(h.registry.get('s1')?.agent).toBe(CODEX_AGENT);
  });

  it('pins the posture discriminant to the shared agent constant', () => {
    // The discriminant must be spelled as a literal (its type is `'codex'`, not
    // `AgentWireName`), and the repo-wide literal scan cannot cover `'codex'`
    // because the terminal axis owns that same value. This is the substitute.
    expect(CODEX_PERMISSION_DEFAULT.agent).toBe(CODEX_AGENT);
    expect(CODEX_PERMISSION_DEFAULT.approvalPolicy).toBe('on-request');
    expect(CODEX_PERMISSION_DEFAULT.sandboxMode).toBe('workspace-write');
  });

  it('carries the thread id from thread/start into session.created as runtimeIdentity', async () => {
    const h = await startedSession();
    const created = payload(h.event('session.created'));

    expect(created.runtimeIdentity).toBe(THREAD_START_RESULT.threadId);
    expect(h.registry.get('s1')?.runtimeIdentity).toBe(created.runtimeIdentity);
  });

  it('emits created then an idle status, both correlated to the create request', async () => {
    const h = await startedSession();
    const order = h.events.map((e) => e.type);

    expect(order).toEqual(['session.created', 'session.status']);
    expect(h.event('session.created')?.requestId).toBe('req-create');
    expect(payload(h.event('session.status')).status).toBe('idle');
  });
});

describe('codexRuntime — handshake identity and isolation', () => {
  it('introduces itself with the product name, never a wire slug', async () => {
    // `clientInfo.name` is folded into the User-Agent codex sends to OpenAI
    // [实测], so this is an external identity: publishing `AgentWireName`'s
    // value there would weld an internal protocol constant to a third party.
    const h = await startedSession();
    const init = h.requestFor('initialize');
    const clientInfo = (init.params?.clientInfo ?? {}) as Record<string, string>;

    expect(clientInfo.name).toBe(CODEX_CLIENT_NAME);
    expect(clientInfo.name).not.toBe(CODEX_AGENT);
    expect(clientInfo.version).toBe('9.9.9-test');
  });

  it('keeps workspace information out of the client title', async () => {
    // No local evidence says `title` stays on this machine (C-g), so it is
    // treated as if it leaves: a fixed product name and nothing derived from
    // what the user is working on.
    const h = await startedSession();
    const clientInfo = (h.requestFor('initialize').params?.clientInfo ?? {}) as Record<
      string,
      string
    >;

    expect(clientInfo.title).toBe(CODEX_CLIENT_TITLE);
    expect(clientInfo.title).not.toContain('/work');
    expect(JSON.stringify(h.requestFor('initialize').params)).not.toContain('/work/repo');
  });

  it('substitutes a placeholder version rather than sending an empty one', () => {
    expect(buildInitializeParams('').clientInfo.version).toBe('0.0.0-unknown');
    expect(buildInitializeParams(' 1.2.3 ').clientInfo.version).toBe('1.2.3');
  });

  it('spawns with CODEX_HOME pointing at the isolated directory', async () => {
    // The projection in `codexHome.ts` is only half the isolation; without this
    // env var codex reads `~/.codex` and every dropped key comes back.
    const h = await startedSession();
    const input = h.connectInputs[0];

    expect(input.env.CODEX_HOME).toBe(HOME_DIR);
    expect(input.cwd).toBe('/work/repo');
    expect(input.plan.codexJsPath.endsWith('codex.js')).toBe(true);
  });

  it('sends the initialized notification after the initialize response', async () => {
    const h = await startedSession();

    expect(h.ops.slice(0, 3)).toEqual([
      'write:initialize',
      'write:initialized',
      'write:thread/start',
    ]);
  });

  it('warns, without failing, when codex reports a home other than the one injected', async () => {
    // "codex read ~/.codex after all" is the single most useful line in a report
    // about a session that inherited `developer_instructions` — and it is only
    // a WARN, because by then the session is already usable.
    const quiet = await startedSession();
    expect(quiet.logs.some((line) => line.includes('different CODEX_HOME'))).toBe(false);

    // Same fake codex (it answers with HOME_DIR), different injected home.
    const loud = makeHarness({ codexHomeDir: '/some/other/home' });
    loud.runtime.createSession({ sessionId: 's-home', workspacePath: '/work/repo' });
    await loud.waitForEvent('session.created');

    expect(loud.logs.some((line) => line.includes('different CODEX_HOME'))).toBe(true);
    expect(loud.event('host.error')).toBeUndefined();
  });

  it('omits model from thread/start when the session has none, and sends it when it does', () => {
    expect(buildThreadStartParams({ cwd: '/w' })).not.toHaveProperty('model');
    expect(buildThreadStartParams({ cwd: '/w', model: 'gpt-5.4' }).model).toBe('gpt-5.4');
    expect(buildThreadStartParams({ cwd: '/w', model: '  ' })).not.toHaveProperty('model');
  });
});

describe('codexRuntime — create failures leave nothing behind', () => {
  it('refuses with agent_unsupported when no codex.js can be resolved', async () => {
    const h = makeHarness({
      resolveLaunch: () => ({
        ok: false,
        code: 'codex_entry_unresolved',
        message: 'Codex entry not found: none of the 3 inspected path(s) is an @openai/codex bin.',
        inspected: [{ path: '/home/someone/.nvm/bin/codex', reason: 'not-a-js-entry' }],
      }),
    });
    h.runtime.createSession({ sessionId: 's-bad', workspacePath: '/work', requestId: 'req-9' });

    const error = h.event('host.error');
    expect(payload(error).code).toBe('agent_unsupported');
    expect(payload(error).fatal).toBe(false);
    // Correlated BOTH ways, exactly like index.ts's refusal: requestId fails the
    // pending command, sessionId scopes the message to this Composer.
    expect(error?.requestId).toBe('req-9');
    expect(error?.sessionId).toBe('s-bad');
    // Nothing was created and no process was started.
    expect(h.registry.get('s-bad')).toBeUndefined();
    expect(h.connectInputs).toHaveLength(0);
  });

  it('keeps the user machine layout out of the event and in the log', async () => {
    // The inspected paths are the most useful line in a support log and the
    // worst thing to push into a UI toast.
    const h = makeHarness({
      resolveLaunch: () => ({
        ok: false,
        code: 'codex_entry_unresolved',
        message: 'Codex entry not found.',
        inspected: [{ path: '/home/someone/secret-project/codex.js', reason: 'not-found' }],
      }),
    });
    h.runtime.createSession({ sessionId: 's-bad2', workspacePath: '/work' });

    expect(JSON.stringify(h.events)).not.toContain('secret-project');
    expect(h.logs.some((line) => line.includes('secret-project'))).toBe(true);
  });

  it('reports a failed handshake, tears the process down and unregisters the session', async () => {
    const h = makeHarness({
      threadStartError: { code: -32602, message: 'invalid params' },
    });
    h.runtime.createSession({ sessionId: 's-fail', workspacePath: '/work', requestId: 'req-f' });
    await h.waitFor(() => h.events.some((e) => e.type === 'host.error'), 'host.error');

    const error = h.event('host.error');
    expect(payload(error).code).toBe('session_create_failed');
    expect(error?.sessionId).toBe('s-fail');
    expect(error?.requestId).toBe('req-f');
    // No half-open session: no created event, no registry row, process killed.
    expect(h.event('session.created')).toBeUndefined();
    expect(h.registry.get('s-fail')).toBeUndefined();
    expect(h.ops.some((op) => op.startsWith('kill:'))).toBe(true);
  });

  it('fails the create when thread/start answers without a thread id', async () => {
    // Without it no turn can ever be addressed, so a "successful" create would
    // hand back a session that is dead on arrival.
    const h = makeHarness({ threadStartResult: { approvalPolicy: 'on-request' } });
    h.runtime.createSession({ sessionId: 's-noid', workspacePath: '/work' });
    await h.waitFor(() => h.events.some((e) => e.type === 'host.error'), 'host.error');

    expect(payload(h.event('host.error')).message).toContain('thread id');
    expect(h.event('session.created')).toBeUndefined();
  });

  it('refuses a duplicate sessionId without touching the existing session', async () => {
    const h = await startedSession();
    h.events.length = 0;
    h.runtime.createSession({ sessionId: 's1', workspacePath: '/work/repo' });

    expect(payload(h.event('host.error')).code).toBe('session_create_failed');
    expect(h.connectInputs).toHaveLength(1);
  });

  it('reports a CODEX_HOME that cannot be prepared instead of running unisolated', async () => {
    // Falsifies "seed failed, carry on": a session that starts without the
    // projection inherits developer_instructions and danger-full-access.
    const h = makeHarness({
      ensureHome: () => {
        throw new Error('EACCES: permission denied');
      },
    });
    h.runtime.createSession({ sessionId: 's-home-fail', workspacePath: '/work' });

    expect(payload(h.event('host.error')).code).toBe('session_create_failed');
    expect(payload(h.event('host.error')).message).toContain('CODEX_HOME');
    expect(h.connectInputs).toHaveLength(0);
  });
});

describe('codexRuntime — thread/status/changed is the only status source', () => {
  it('maps an active frame with no flags to running', async () => {
    const h = await startedSession();
    h.events.length = 0;
    h.push({
      method: 'thread/status/changed',
      params: {
        threadId: THREAD_START_RESULT.threadId,
        status: { type: 'active', activeFlags: [] },
      },
    });

    expect(payload(h.event('session.status')).status).toBe('running');
    expect(h.registry.get('s1')?.status).toBe('running');
  });

  it('prefers waiting_permission when both flags are set', async () => {
    // Constructed case — no real frame carries both flags (arbitration doc
    // §4.5). An approval blocks execution and carries destructive consequences,
    // so it is the state worth showing.
    const h = await startedSession();
    h.events.length = 0;
    h.push({
      method: 'thread/status/changed',
      params: {
        status: { type: 'active', activeFlags: ['waitingOnUserInput', 'waitingOnApproval'] },
      },
    });

    expect(payload(h.event('session.status')).status).toBe('waiting_permission');
  });

  it('handles the idle frame, which has NO activeFlags key at all', async () => {
    // A mapper that reads `status.activeFlags.includes(...)` first throws a
    // TypeError at the exact moment a turn ends.
    const h = await startedSession();
    h.events.length = 0;
    expect(() =>
      h.push({ method: 'thread/status/changed', params: { status: { type: 'idle' } } })
    ).not.toThrow();

    expect(payload(h.event('session.status')).status).toBe('idle');
  });

  it('says nothing on a malformed status instead of guessing', async () => {
    const h = await startedSession();
    h.events.length = 0;
    h.push({ method: 'thread/status/changed', params: { status: { type: 'quantum' } } });

    // No opinion keeps the previous state; guessing `running` would overwrite a
    // live waiting state and strand a card.
    expect(h.eventsOf('session.status')).toHaveLength(0);
  });

  it('warns about unknown flags but still emits the reading', async () => {
    const h = await startedSession();
    h.events.length = 0;
    h.push({
      method: 'thread/status/changed',
      params: {
        status: { type: 'active', activeFlags: ['waitingOnApproval', 'waitingOnTeaBreak'] },
      },
    });

    expect(payload(h.event('session.status')).status).toBe('waiting_permission');
    expect(h.logs.some((line) => line.includes('unknown flags'))).toBe(true);
  });

  it('drops a status that belongs to another thread', async () => {
    // One session ≡ one thread (C12, fork banned). Projecting a foreign
    // thread's state onto this session would mislabel it.
    const h = await startedSession();
    h.events.length = 0;
    h.push({
      method: 'thread/status/changed',
      params: { threadId: 'someone-elses-thread', status: { type: 'active', activeFlags: [] } },
    });

    expect(h.eventsOf('session.status')).toHaveLength(0);
    expect(h.logs.some((line) => line.includes('foreign thread'))).toBe(true);
  });
});

describe('codexRuntime — server requests and the pending table', () => {
  const approval = (id: number) => ({
    id,
    method: 'item/commandExecution/requestApproval',
    params: { threadId: THREAD_START_RESULT.threadId, command: 'rm -rf /' },
  });

  it('answers an unknown server method with method-not-found instead of registering it', async () => {
    const h = await startedSession();
    h.push({ id: 5, method: 'item/telepathy/request', params: {} });

    const reply = h.replies().at(-1) as { id?: number; error?: { code: number } } | undefined;
    expect(reply?.id).toBe(5);
    expect(reply?.error?.code).toBe(JSONRPC_METHOD_NOT_FOUND);
  });

  it('drains a registered request on close — one reply, with a refusal body, then the kill', async () => {
    // The two halves of the invariant: the table ends empty AND every entry got
    // exactly one frame. Clearing without replying passes a naive `size === 0`
    // check while codex waits on `waitingOnApproval` forever.
    const h = await startedSession();
    h.push(approval(0));
    h.runtime.close({ sessionId: 's1', requestId: 'req-close' });

    const replies = h.replies();
    expect(replies).toHaveLength(1);
    expect(replies[0]).toMatchObject({ id: 0, result: { decision: 'cancel' } });
    // ORDER: the refusal frame is written BEFORE the process is killed. Reverse
    // them and the write lands on a dead stdin — silently dropped.
    expect(h.ops.indexOf('reply:0')).toBeLessThan(h.ops.indexOf('kill:session closed'));
    expect(payload(h.eventsOf('session.status').at(-1)).status).toBe('disconnected');
    expect(h.registry.get('s1')).toBeUndefined();
  });

  it('drains on stop with the aborted reason and keeps the connection alive', async () => {
    const h = await startedSession();
    h.push(approval(0));
    h.events.length = 0;
    h.runtime.stop({ sessionId: 's1', requestId: 'req-stop' });

    expect(h.replies()).toHaveLength(1);
    expect(h.ops.some((op) => op.startsWith('kill:'))).toBe(false);
    // Stop is not close: the session survives it.
    expect(h.registry.get('s1')).toBeDefined();
    expect(h.event('session.status')?.requestId).toBe('req-stop');
  });

  it('answers a second, unrelated request too — the drain is not first-only', async () => {
    const h = await startedSession();
    h.push(approval(0));
    h.push({ id: 1, method: 'item/tool/requestUserInput', params: { questions: [] } });
    h.runtime.close({ sessionId: 's1' });

    const replies = h.replies();
    expect(replies.map((r) => r.id)).toEqual([0, 1]);
    // Per-kind fail-safe bodies: a cancelled approval and an empty answer map,
    // neither of which can be read as consent.
    expect(replies[0].result).toEqual({ decision: 'cancel' });
    expect(replies[1].result).toEqual({ answers: {} });
  });

  it('drains everything when the process dies on its own, and reports the session failed', async () => {
    const h = await startedSession();
    h.push(approval(0));
    h.events.length = 0;
    // A crash, through the real connection core — not a close we initiated.
    h.exit({ code: 1, signal: null });

    // The entry IS settled (the card resolves), but the frame cannot be
    // delivered: the process is already gone. That asymmetry is exactly why the
    // close path above must drain BEFORE it disposes — there, the frame lands.
    expect(h.logs.some((line) => line.includes('codex pending drained'))).toBe(true);
    expect(h.logs.some((line) => line.includes('"reason":"aborted"'))).toBe(true);
    expect(h.replies()).toHaveLength(0);
    expect(payload(h.event('session.failed')).error).toContain('exited');
    expect(h.registry.get('s1')?.status).toBe('disconnected');
  });

  it('drains and disposes every session on host shutdown', async () => {
    const h = await startedSession();
    h.push(approval(0));
    h.runtime.dispose();

    expect(h.replies()).toHaveLength(1);
    expect(h.ops.some((op) => op === 'kill:host shutting down')).toBe(true);
    // Idempotent: a close arriving after shutdown must not drain twice.
    h.runtime.close({ sessionId: 's1' });
    expect(h.replies()).toHaveLength(1);
  });

  it('closes a session that has no live connection without throwing', async () => {
    const h = await startedSession();
    h.exit({ code: 1, signal: null });
    h.events.length = 0;
    h.runtime.close({ sessionId: 's1' });

    expect(payload(h.event('session.status')).status).toBe('disconnected');
    expect(h.registry.get('s1')).toBeUndefined();
  });
});

describe('codexRuntime — the deliberate holes are explicit refusals', () => {
  it('no longer refuses send — the turn loop landed in slice 2c', async () => {
    // Slice 2a deliberately refused send() because the event normalizer was
    // unowned by any slice; this assertion pinned that hole so it could not be
    // half-filled. 2c filled it, so the assertion is re-judged rather than
    // deleted: what it now guards is that the refusal did not survive as a
    // silent no-op. The turn loop's own behaviour is covered below.
    const h = await startedSession();
    h.events.length = 0;
    await h.runtime.send({ sessionId: 's1', text: 'hi', requestId: 'req-send' });

    const error = h.event('host.error');
    expect(payload(error)?.code).not.toBe('not_implemented');
  });

  it('refuses resume with agent_unsupported and explains why', async () => {
    // A Codex resume that emitted only `session.resumed` would leave the
    // renderer on a blank transcript with no error at all — history replay is
    // slice 5a.
    const h = makeHarness();
    h.runtime.resumeSession({ sessionId: 's-resume', requestId: 'req-resume' });

    const error = h.event('host.error');
    expect(payload(error).code).toBe('agent_unsupported');
    expect(payload(error).fatal).toBe(false);
    expect(error?.sessionId).toBe('s-resume');
    expect(String(payload(error).message)).toContain('later slice');
    // Nothing registered, nothing spawned.
    expect(h.registry.get('s-resume')).toBeUndefined();
    expect(h.connectInputs).toHaveLength(0);
  });

  it('refuses both respond commands, correlated to the session', async () => {
    const h = await startedSession();
    h.events.length = 0;
    h.runtime.respondPermission({ sessionId: 's1', requestId: 'req-p' });
    h.runtime.respondQuestion({ sessionId: 's1', requestId: 'req-q' });

    expect(h.eventsOf('host.error').map((e) => payload(e).code)).toEqual([
      'not_implemented',
      'not_implemented',
    ]);
  });

  it('reports an unknown session on stop the way the Claude runtime does', async () => {
    const h = makeHarness();
    h.runtime.stop({ sessionId: 'nope', requestId: 'req-stop' });

    expect(payload(h.event('host.error')).code).toBe('session_not_found');
  });
});

describe('codexRuntime — send() opens a turn on the wire (slice 2c)', () => {
  it('sends turn/start with every required field and no field the schema does not name', async () => {
    const h = await turnSession();
    await h.runtime.send({ sessionId: 's1', text: PROMPT, requestId: 'req-send' });

    const params = (h.requestFor('turn/start').params ?? {}) as Record<string, unknown>;

    // Falsifies a DROPPED required field: `turn/start` without `threadId` is a
    // -32602 on a machine we cannot reach, while our log claims a turn opened.
    for (const key of turnSchema.TurnStartParams.required) expect(params).toHaveProperty(key);
    // Falsifies an INVENTED field: anything outside the generated property list
    // is a name we made up, and the server drops it without a word.
    for (const key of Object.keys(params)) {
      expect(turnSchema.TurnStartParams.propertyNames).toContain(key);
    }
    expect(params.threadId).toBe(FIXTURE_THREAD);
    expect(params.input).toEqual([{ type: 'text', text: PROMPT }]);
  });

  it('keeps the posture out of the turn, because a turn-level override is sticky', async () => {
    // The schema says `approvalPolicy` / `sandboxPolicy` / `cwd` apply "for this
    // turn AND SUBSEQUENT TURNS". Sending them would give the posture a second
    // source that silently outlives the turn that set it; `thread/start` stays
    // the only place it is decided. `effort` and `model` are accepted by send()
    // and dropped for the same reason (plus: `effort`'s vocabulary is per-model
    // and we have never read one out of `model/list`).
    const h = await turnSession();
    await h.runtime.send({ sessionId: 's1', text: PROMPT, effort: 'high', model: 'gpt-5.4' });

    const params = (h.requestFor('turn/start').params ?? {}) as Record<string, unknown>;
    for (const sticky of ['approvalPolicy', 'sandboxPolicy', 'cwd', 'model', 'effort']) {
      expect(params).not.toHaveProperty(sticky);
    }
  });

  it('builds the one UserInput variant we can build, claiming nothing extra', async () => {
    const h = await turnSession();
    await h.runtime.send({ sessionId: 's1', text: PROMPT });

    const { input } = (h.requestFor('turn/start').params ?? {}) as {
      input: Array<Record<string, unknown>>;
    };
    expect(input).toHaveLength(1);
    for (const key of turnSchema.UserInputText.required) expect(input[0]).toHaveProperty(key);
    // `text_elements` is optional (`default: []`) and describes UI spans we do
    // not produce; sending an empty array would claim we parsed the text and
    // found none.
    expect(input[0]).not.toHaveProperty('text_elements');
  });

  it('emits nothing of its own — no user echo and no running status', async () => {
    // Codex sends the prompt back as an `item/started` userMessage [实测 frame
    // 1] and the normalizer renders THAT, so a local echo would draw the message
    // twice. A `running` here would race codex's own first status frame and
    // could overwrite a `waiting_permission` that had already landed (C10 r3).
    const h = await turnSession();
    await h.runtime.send({ sessionId: 's1', text: PROMPT, requestId: 'req-send' });

    expect(h.events).toEqual([]);
  });

  it('replays the recorded turn into an assistant message, a tool row and one terminal', async () => {
    const h = await turnSession();
    await h.runtime.send({ sessionId: 's1', text: PROMPT });
    replayRecordedTurn(h);

    const types = typesOf(h.events);
    // The user echo exists, and it came from codex's frame, not from send().
    expect(payload(h.eventsOf('message.started')[0]).role).toBe('user');
    expect(types).toContain('thinking.started');
    // The fileChange item is this turn's only tool row [实测 frames 7 and 12].
    expect(payload(h.event('tool.started')).name).toBe('apply_patch');
    expect(payload(h.event('tool.started')).toolCallId).toBe(FIXTURE_ITEM);
    expect(payload(h.event('tool.completed')).toolCallId).toBe(FIXTURE_ITEM);
    // Assistant prose actually reached the renderer. Asserting the event exists
    // is not enough: an empty delta renders an empty bubble.
    const assistantText = h
      .eventsOf('message.delta')
      .filter((event) => String(payload(event).messageId).startsWith('codex-asst-'))
      .map((event) => String(payload(event).text))
      .join('');
    expect(assistantText.length).toBeGreaterThan(0);
    // Exactly one terminal, and the bubble is closed before it — the other order
    // leaves a message the renderer paints as still streaming.
    expect(terminalsOf(h.events)).toEqual(['session.completed']);
    expect(types.lastIndexOf('message.completed')).toBeLessThan(types.indexOf('session.completed'));
    expect(types.at(-1)).toBe('session.completed');
  });

  it('emits one session.status per status FRAME and not one more', async () => {
    // C10 rule 3: `codexStatus` + `onStatusChanged` are the ONLY writer. These
    // four readings are the fixture's four `thread/status/changed` frames
    // [实测 frames 0, 8, 11, 17]; a fifth event would mean the normalizer or
    // send() derived one, which is the second-truth defect the rule exists for.
    const h = await turnSession();
    await h.runtime.send({ sessionId: 's1', text: PROMPT });
    replayRecordedTurn(h);

    expect(h.eventsOf('session.status').map((event) => payload(event).status)).toEqual([
      'running',
      'waiting_permission',
      'running',
      'idle',
    ]);
  });

  it('emits NO session.status at all when the stream carries no status frame', async () => {
    // The sharper half of the same rule: with the four frames removed, a single
    // status event proves somebody else is deriving one. Replaying a doctored
    // stream is the only way to tell "the mapper produced those four" from
    // "four happened to match".
    const h = await turnSession();
    await h.runtime.send({ sessionId: 's1', text: PROMPT });
    replayRecordedTurn(h, { drop: ['thread/status/changed'] });

    expect(h.eventsOf('session.status')).toHaveLength(0);
    // Not vacuous: the turn still ran and still ended.
    expect(h.eventsOf('session.completed')).toHaveLength(1);
  });

  it('accepts the next send once the turn ended — the session is not left busy', async () => {
    const h = await turnSession();
    await h.runtime.send({ sessionId: 's1', text: PROMPT });
    replayRecordedTurn(h);
    expect(h.registry.get('s1')?.running).toBe(false);

    h.events.length = 0;
    await h.runtime.send({ sessionId: 's1', text: 'and now the tests', requestId: 'req-2' });

    // Falsifies "the turn record survives its own terminal": that leaves every
    // later send refused as `session_busy` for the life of the session.
    expect(h.eventsOf('host.error')).toHaveLength(0);
    const starts = h.requestsFor('turn/start');
    expect(starts).toHaveLength(2);
    expect((starts[1].params as { input: Array<{ text: string }> }).input[0].text).toBe(
      'and now the tests'
    );
  });
});

describe('codexRuntime — one turn at a time, and every refusal is audible', () => {
  it('refuses a second send during a turn and writes no second turn/start', async () => {
    const h = await turnSession();
    await h.runtime.send({ sessionId: 's1', text: PROMPT, requestId: 'req-1' });
    replayRecordedTurn(h, { upTo: 8 });
    h.events.length = 0;
    await h.runtime.send({ sessionId: 's1', text: 'interrupting', requestId: 'req-2' });

    // Refused LOUDLY and with the exact code the renderer's bounded send-retry
    // keys on (`queueRelease.ts`): a silent drop leaves the Composer spinning on
    // req-2 forever, and a second `turn/start` runs two turns on one thread.
    const error = h.event('host.error');
    expect(payload(error).code).toBe('session_busy');
    expect(error?.requestId).toBe('req-2');
    expect(error?.sessionId).toBe('s1');
    expect(h.requestsFor('turn/start')).toHaveLength(1);
    // The refusal did not disturb the turn that is actually running.
    expect(terminalsOf(h.events)).toEqual([]);
  });

  it('refuses a send that arrives while the thread is still starting, retryably', async () => {
    // Same code deliberately: this one resolves on its own within a round trip,
    // which is exactly what the renderer's bounded `session_busy` retry exists
    // for. A hard code here would drop the user's first message.
    const h = makeHarness();
    h.runtime.createSession({ sessionId: 's-slow', workspacePath: '/work/repo' });
    await h.runtime.send({ sessionId: 's-slow', text: PROMPT, requestId: 'req-early' });

    expect(payload(h.event('host.error')).code).toBe('session_busy');
    expect(String(payload(h.event('host.error')).message)).toContain('still starting');
    expect(h.requestsFor('turn/start')).toHaveLength(0);
  });

  it('refuses every send it cannot honour, correlated, without opening a turn', async () => {
    const h = await turnSession();
    h.events.length = 0;
    await h.runtime.send({ sessionId: 'nope', text: 'x', requestId: 'r1' });
    // Attachments are refused WHOLE rather than sent without them: codex takes
    // images by url or path, ours are inline base64, and dropping them silently
    // would have the user watch the model answer about an image it never got.
    await h.runtime.send({
      sessionId: 's1',
      text: 'look',
      attachments: [{ mediaType: 'image/png', data: 'AAAA' }],
      requestId: 'r2',
    });
    await h.runtime.send({ sessionId: 's1', text: '   ', requestId: 'r3' });

    expect(h.eventsOf('host.error').map((event) => payload(event).code)).toEqual([
      'session_not_found',
      'not_implemented',
      'invalid_payload',
    ]);
    expect(h.eventsOf('host.error').map((event) => event.requestId)).toEqual(['r1', 'r2', 'r3']);
    // None of the three left a half-open turn behind.
    expect(h.requestsFor('turn/start')).toHaveLength(0);
    expect(h.registry.get('s1')?.running).toBeFalsy();
  });
});

describe('codexRuntime — stop() does both halves, in the order that makes them work', () => {
  it('drains the parked request AND interrupts the turn — never just one of the two', async () => {
    const h = await stoppableTurn();
    h.events.length = 0;
    h.runtime.stop({ sessionId: 's1', requestId: 'req-stop' });

    // Half one — codex is parked on our answer to id 0, and it gets exactly one.
    // Without it the model stays in `waitingOnApproval` after the user pressed
    // Stop, i.e. Stop stopped nothing.
    const replies = h.replies();
    expect(replies).toHaveLength(1);
    expect(replies[0]).toMatchObject({ id: APPROVAL_ID, result: { decision: 'cancel' } });
    // Half two — the model is actually told to abandon the turn. A drain without
    // this leaves it working after the user pressed Stop.
    expect(h.requestFor('turn/interrupt').params).toEqual({
      threadId: FIXTURE_THREAD,
      turnId: FIXTURE_TURN,
    });
    // ORDER, and it is load-bearing: a turn parked on an approval is parked on
    // US, so an interrupt written first queues behind a task that is waiting for
    // the very reply we had not sent yet.
    expect(h.ops.indexOf(`reply:${APPROVAL_ID}`)).toBeLessThan(
      h.ops.indexOf('write:turn/interrupt')
    );
  });

  it('addresses the interrupt with both ids the schema requires, and nothing else', async () => {
    // A one-id interrupt is a schema error: it interrupts nothing, while the log
    // says we asked [实测 codex-turn-schema.json — both ids are required].
    const h = await stoppableTurn();
    h.runtime.stop({ sessionId: 's1' });

    const params = (h.requestFor('turn/interrupt').params ?? {}) as Record<string, unknown>;
    for (const key of turnSchema.TurnInterruptParams.required) expect(params).toHaveProperty(key);
    expect(Object.keys(params).sort()).toEqual(
      [...turnSchema.TurnInterruptParams.propertyNames].sort()
    );
  });

  it('sends no interrupt at all when the turn has never named itself', async () => {
    // Silence on `turn/start` is a real posture [未测 whether codex answers at
    // turn start or at turn end], and with no notification in yet the turn id is
    // unknown. Sending a half-addressed frame is worse than sending none: a
    // -32602 plus a log line claiming we stopped the turn.
    const h = await turnSession({ answerTurnStart: false });
    void h.runtime.send({ sessionId: 's1', text: PROMPT });
    h.events.length = 0;
    h.runtime.stop({ sessionId: 's1', requestId: 'req-stop' });

    expect(h.requestsFor('turn/interrupt')).toHaveLength(0);
    expect(h.logs.some((line) => line.includes('turn id unknown'))).toBe(true);
    // The half that must never depend on codex answering still happened.
    expect(h.eventsOf('session.stopped')).toHaveLength(1);
  });

  it('interrupts on a turn id learned from the notification stream', async () => {
    // The stream reliably beats the response, so the id has to be picked up
    // there as well — otherwise Stop is silently unavailable for the entire
    // window in which `turn/start` has not been answered.
    const h = await turnSession({ answerTurnStart: false });
    void h.runtime.send({ sessionId: 's1', text: PROMPT });
    replayRecordedTurn(h, { upTo: 2 });
    h.runtime.stop({ sessionId: 's1' });

    const params = (h.requestFor('turn/interrupt').params ?? {}) as Record<string, unknown>;
    expect(params.turnId).toBe(FIXTURE_TURN);
  });

  it('frees the session locally, without waiting for a frame that may never come', async () => {
    const h = await stoppableTurn();
    h.events.length = 0;
    h.runtime.stop({ sessionId: 's1', requestId: 'req-stop' });
    await h.runtime.send({ sessionId: 's1', text: 'again', requestId: 'req-2' });

    expect(h.eventsOf('host.error')).toHaveLength(0);
    expect(h.requestsFor('turn/start')).toHaveLength(2);
  });

  it('does not leave the session in a busy status after it stopped the turn', async () => {
    // The registry's last real reading here is `waiting_permission` (the
    // approval frame). Echoing it AFTER the terminal re-freezes the renderer:
    // `chatSessions.isBusyStatus` counts `waiting_permission` as busy and
    // `sendMessage` refuses outright, so the user cannot send again until a
    // frame arrives that stop() itself declines to wait for. Falsifies the
    // method's own claim that "Stop always frees the session".
    const h = await stoppableTurn();
    h.events.length = 0;
    h.runtime.stop({ sessionId: 's1', requestId: 'req-stop' });

    const status = h.event('session.status');
    // Still the registry's OWN reading — no invented `stopping` (C10 rule 3).
    expect(payload(status).status).toBe('waiting_permission');
    expect(status?.requestId).toBe('req-stop');
    // ...but it must not be the last word the renderer hears.
    const types = typesOf(h.events);
    expect(types.indexOf('session.status')).toBeLessThan(types.indexOf('session.stopped'));
  });

  it('puts nothing on the wire that the exported builders did not produce', async () => {
    // The builders are what the generated schema is pinned against, above. If
    // send() or stop() hand-rolled their params alongside them, those schema
    // assertions would keep passing while the wire drifted away from them.
    // Capture compared to capture, never literal to literal — the same paradigm
    // the permission-posture gate item uses.
    const h = await stoppableTurn();
    h.runtime.stop({ sessionId: 's1' });

    expect(h.requestFor('turn/start').params).toEqual(
      buildTurnStartParams({ threadId: FIXTURE_THREAD, text: PROMPT })
    );
    expect(h.requestFor('turn/interrupt').params).toEqual(
      buildTurnInterruptParams({ threadId: FIXTURE_THREAD, turnId: FIXTURE_TURN })
    );
  });

  it('drops the abandoned turn s late frames instead of reporting a second terminal', async () => {
    const h = await stoppableTurn();
    h.events.length = 0;
    h.runtime.stop({ sessionId: 's1' });
    // Everything codex had already queued behind the approval, `turn/completed`
    // included. The registered cost is that these are lost; the failure would be
    // a second terminal for a turn the renderer has already retired.
    replayRecordedTurn(h, { from: 10 });

    expect(terminalsOf(h.events)).toEqual(['session.stopped']);
    expect(h.logs.some((line) => line.includes('outside a turn'))).toBe(true);
    // Codex's own status frames still land, which is what converges the session
    // after a local stop.
    expect(payload(h.eventsOf('session.status').at(-1)).status).toBe('idle');
  });
});

describe('codexRuntime — the link dies in the middle of a turn', () => {
  it('closes the turn as failed, closes the bubble first, and reports the death once', async () => {
    const h = await stoppableTurn();
    h.events.length = 0;
    h.exit({ code: 1, signal: null });

    const types = typesOf(h.events);
    // Exactly one death report. `onExit` closes the turn and the turn carries
    // the terminal; the other arrangement (session.failed here, turn closed by
    // teardown) reports the same death twice with a streaming bubble between.
    expect(terminalsOf(h.events)).toEqual(['session.failed']);
    expect(String(payload(h.event('session.failed')).error)).toContain('exited');
    expect(types.indexOf('message.completed')).toBeLessThan(types.indexOf('session.failed'));
    expect(h.registry.get('s1')?.status).toBe('disconnected');
  });

  it('settles every parked request, exactly once, even though no frame can land', async () => {
    const h = await stoppableTurn();
    h.exit({ code: 1, signal: null });

    // The entry IS settled, so nothing is left waiting in the table; the frame
    // cannot be written because the process is already gone. That asymmetry is
    // precisely why the close path drains BEFORE it disposes — there it lands.
    expect(h.logs.some((line) => line.includes('codex pending drained'))).toBe(true);
    expect(h.logs.some((line) => line.includes('"reason":"aborted"'))).toBe(true);
    expect(h.replies()).toHaveLength(0);
    // Idempotent: a close arriving after the crash must not drain a second time,
    // which would answer an id nobody is holding.
    h.runtime.close({ sessionId: 's1' });
    expect(h.logs.filter((line) => line.includes('codex pending drained'))).toHaveLength(1);
  });

  it('leaves nothing behind: the next send is refused, not queued', async () => {
    const h = await stoppableTurn();
    h.exit({ code: 1, signal: null });
    h.events.length = 0;
    await h.runtime.send({ sessionId: 's1', text: 'still there?', requestId: 'req-2' });

    expect(payload(h.event('host.error')).code).toBe('session_not_found');
    expect(h.requestsFor('turn/start')).toHaveLength(1);
  });

  it('reports the death once when turn/start was never answered', async () => {
    // The connection rejects every outstanding promise BEFORE it calls onExit,
    // so send()'s catch and the exit path race for the same turn. Two reports
    // fail one session twice; a report from the catch alone would blame
    // `turn/start` for a process that crashed under it.
    const h = await turnSession({ answerTurnStart: false });
    const sending = h.runtime.send({ sessionId: 's1', text: PROMPT, requestId: 'req-send' });
    replayRecordedTurn(h, { upTo: 2 });
    h.events.length = 0;
    h.exit({ code: null, signal: 'SIGKILL' });
    await sending;

    expect(terminalsOf(h.events)).toEqual(['session.failed']);
    expect(String(payload(h.event('session.failed')).error)).toContain('exited');
    expect(h.logs.some((line) => line.includes('failed after the turn ended'))).toBe(true);
  });
});

describe('codexRuntime — close() still drains before it disposes, now with a turn open', () => {
  it('writes the refusal, then the interrupt, then the kill', async () => {
    // 2a proved this ordering for a session with no turn. 2c inserted a frame
    // between the drain and the kill, so it is re-proved with a turn in flight:
    // `dispose()` kills the process, and after that there is no stdin left for
    // either the refusal or the interrupt.
    const h = await stoppableTurn();
    h.runtime.close({ sessionId: 's1', requestId: 'req-close' });

    const reply = h.ops.indexOf(`reply:${APPROVAL_ID}`);
    const interrupt = h.ops.indexOf('write:turn/interrupt');
    const kill = h.ops.indexOf('kill:session closed');
    expect(reply).toBeGreaterThanOrEqual(0);
    expect(reply).toBeLessThan(interrupt);
    expect(interrupt).toBeLessThan(kill);
  });

  it('closes the open turn so nothing streams forever, then reports disconnected', async () => {
    const h = await stoppableTurn();
    h.events.length = 0;
    h.runtime.close({ sessionId: 's1', requestId: 'req-close' });

    const types = typesOf(h.events);
    expect(terminalsOf(h.events)).toEqual(['session.stopped']);
    expect(types.indexOf('message.completed')).toBeLessThan(types.indexOf('session.stopped'));
    expect(types.at(-1)).toBe('session.status');
    expect(payload(h.events.at(-1)).status).toBe('disconnected');
    expect(h.registry.get('s1')).toBeUndefined();
  });

  it('closes an open turn on host shutdown too', async () => {
    const h = await stoppableTurn();
    h.events.length = 0;
    h.runtime.dispose();

    expect(terminalsOf(h.events)).toEqual(['session.stopped']);
    expect(h.replies()).toHaveLength(1);
    expect(h.ops.indexOf(`reply:${APPROVAL_ID}`)).toBeLessThan(
      h.ops.indexOf('kill:host shutting down')
    );
  });

  it('does not report a turn that was retired while turn/start was still in flight', async () => {
    // `dispose()` rejects the outstanding `turn/start`, but a rejection is
    // delivered as a microtask, i.e. AFTER the synchronous teardown has already
    // emitted the terminal. A second report here would fail a session that has
    // just been told what happened.
    const h = await turnSession({ answerTurnStart: false });
    const sending = h.runtime.send({ sessionId: 's1', text: PROMPT });
    h.events.length = 0;
    h.runtime.close({ sessionId: 's1' });
    await sending;

    expect(terminalsOf(h.events)).toEqual(['session.stopped']);
  });
});

describe('codexRuntime — turns are isolated from one another', () => {
  /** Codex never reuses a turn id; the second replay must not either. */
  const SECOND_TURN = '019fd82d-aeb2-7f32-8eed-000000000002';

  /** Two full turns on one session, the second re-stamped with its own turn id. */
  async function twoTurns(): Promise<{ h: Harness; first: string[]; second: string[] }> {
    // `answerTurnStart: false` so each turn's id is learned from ITS OWN stream
    // rather than from one canned response reused for both — otherwise the
    // second turn would be handed the first turn's id by the harness.
    const h = await turnSession({ answerTurnStart: false });
    void h.runtime.send({ sessionId: 's1', text: PROMPT });
    replayRecordedTurn(h);
    const first = h.events.map((event) => String(payload(event).messageId ?? ''));
    h.events.length = 0;
    void h.runtime.send({ sessionId: 's1', text: 'second turn' });
    replayRecordedTurn(h, { turnId: SECOND_TURN });
    const second = h.events.map((event) => String(payload(event).messageId ?? ''));
    return { h, first, second };
  }

  it('gives the second turn a fresh normalizer, so the first cannot suppress it', async () => {
    // A normalizer kept across turns would still hold turn 1's `settledTools`
    // and `streamedItems` keyed on these very item ids, so turn 2 would render
    // no tool row and no assistant text: a turn that silently draws nothing.
    const { h } = await twoTurns();

    expect(h.eventsOf('tool.started')).toHaveLength(1);
    expect(h.eventsOf('tool.completed')).toHaveLength(1);
    expect(terminalsOf(h.events)).toEqual(['session.completed']);
    expect(h.requestsFor('turn/start')).toHaveLength(2);
  });

  it('addresses the second turn s blocks to a second assistant message', async () => {
    const { first, second } = await twoTurns();

    const assistant = second.filter((id) => id.startsWith('codex-asst-'));
    expect(assistant.length).toBeGreaterThan(0);
    // Nothing in turn 2 addresses turn 1's envelope: a block appended to a
    // message the renderer already completed is a block dropped on the floor.
    for (const id of assistant) expect(first).not.toContain(id);
  });

  it('drops a frame that lands after the terminal instead of folding it into the next turn', async () => {
    // The registered cost of retiring the turn on `turn/completed`: a trailing
    // `thread/tokenUsage/updated` is lost. Losing a usage refresh is cheaper
    // than resurrecting a finished turn — but it has to be a DROP, not an event
    // attributed to whatever turn comes next.
    const h = await turnSession();
    await h.runtime.send({ sessionId: 's1', text: PROMPT });
    replayRecordedTurn(h);
    h.events.length = 0;
    h.push({
      method: 'thread/tokenUsage/updated',
      params: { threadId: FIXTURE_THREAD, totalTokenUsage: { totalTokens: 1 } },
    });

    expect(h.eventsOf('usage.updated')).toHaveLength(0);
    expect(h.logs.some((line) => line.includes('outside a turn'))).toBe(true);
  });

  it('does not let another thread s turn/completed retire this session s turn', async () => {
    // C12 — one session ≡ one thread — is already enforced for status frames
    // (`WARN codex status for a foreign thread, ignored`). The turn loop must
    // not be the hole in it: the normalizer DROPS a foreign frame, so retiring
    // the turn on it and claiming `terminalAlreadyEmitted` asserts an event that
    // was never sent. The result is the worst combination available — no
    // terminal AND no turn record: the assistant bubble streams forever, the
    // renderer keeps the session busy, and the real `turn/completed` that
    // follows is dropped as "outside a turn".
    const h = await turnSession();
    await h.runtime.send({ sessionId: 's1', text: PROMPT });
    replayRecordedTurn(h, { upTo: 8 });
    h.events.length = 0;
    h.push({
      method: 'turn/completed',
      params: {
        threadId: 'someone-elses-thread',
        turn: { id: 'other-turn', items: [], status: 'completed' },
      },
    });

    // Ignored outright: no terminal, because none belongs to us...
    expect(terminalsOf(h.events)).toEqual([]);
    // ...and the turn is still ours to finish, so our own frames still land.
    replayRecordedTurn(h, { from: 8 });
    expect(h.eventsOf('session.completed')).toHaveLength(1);
  });
});

describe('compareSandboxEcho', () => {
  const sent = CODEX_PERMISSION_DEFAULT;

  it('matches the recorded read-only echo against a read-only policy', () => {
    // The one echo we actually hold [实测
    // fixtures/codex/codex-thread-start-echo.partial.json]: request-side
    // `read-only` versus result-side `readOnly`.
    const recorded = {
      approvalPolicy: 'untrusted',
      sandbox: { type: 'readOnly', networkAccess: false },
      activePermissionProfile: null,
    };
    const result = compareSandboxEcho(
      {
        agent: 'codex',
        approvalPolicy: 'untrusted',
        sandboxMode: 'read-only',
        networkAccess: false,
      },
      recorded
    );

    expect(result.verdict).toBe('match');
    expect(result.detail).toContain('approvalPolicy');
  });

  it('reports a mismatch when the server applied a different sandbox tier', () => {
    const result = compareSandboxEcho(sent, {
      approvalPolicy: 'on-request',
      sandbox: { type: 'dangerFullAccess', networkAccess: true },
    });

    expect(result.verdict).toBe('mismatch');
    expect(result.detail).toContain('sandbox');
  });

  it('names networkAccess as a server default, not a dropped request field', () => {
    // Anyone reading the WARN would otherwise hunt for a bug on the request
    // side, where the field does not exist at all.
    const result = compareSandboxEcho(sent, {
      approvalPolicy: 'on-request',
      sandbox: { type: 'workspace-write', networkAccess: true },
    });

    expect(result.verdict).toBe('mismatch');
    expect(result.detail).toContain('never sent by us');
  });

  it('returns unverifiable — never match — when nothing comparable came back', () => {
    // The one reading this function must never produce: "we could not check"
    // presented as "we checked and agreed".
    for (const echo of [undefined, null, 42, 'ok', {}, { thread: { id: 'x' } }]) {
      expect(compareSandboxEcho(sent, echo).verdict).toBe('unverifiable');
    }
  });

  it('looks inside a thread wrapper, since the recorded fragment lost its parent', () => {
    const result = compareSandboxEcho(sent, {
      thread: { id: 't', approvalPolicy: 'on-request', sandbox: 'workspace-write' },
    });

    expect(result.verdict).toBe('match');
  });

  it('still counts partial verification as a match but says what was not echoed', () => {
    const result = compareSandboxEcho(sent, { approvalPolicy: 'on-request' });

    expect(result.verdict).toBe('match');
    expect(result.detail).toContain('not echoed: sandbox, networkAccess');
  });
});
