import * as fs from 'node:fs/promises';
import * as os from 'node:os';
import * as path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { ClaudeSessionScanner } from '../ClaudeSessionScanner';

describe('ClaudeSessionScanner', () => {
  let tempDir: string;
  let originalClaudeConfigDir: string | undefined;

  beforeEach(async () => {
    originalClaudeConfigDir = process.env.CLAUDE_CONFIG_DIR;
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'claude-scanner-'));
    process.env.CLAUDE_CONFIG_DIR = tempDir;
    await fs.mkdir(path.join(tempDir, 'projects'), { recursive: true });
  });

  afterEach(async () => {
    if (originalClaudeConfigDir === undefined) {
      delete process.env.CLAUDE_CONFIG_DIR;
    } else {
      process.env.CLAUDE_CONFIG_DIR = originalClaudeConfigDir;
    }

    await fs.rm(tempDir, { recursive: true, force: true });
  });

  it('prefers cwd from jsonl entries over directory name fallback', async () => {
    const projectId = 'D--Projects-jyw-ai-jyw-ai-client';
    const projectDir = path.join(tempDir, 'projects', projectId);
    await fs.mkdir(projectDir, { recursive: true });

    const sessionId = '5654315f-e717-4a41-b7ad-f9ac5d7b9f04';
    const filePath = path.join(projectDir, `${sessionId}.jsonl`);

    const cwd = 'D:\\Projects\\jyw_ai\\jyw-ai-client';
    const jsonl = [
      JSON.stringify({ type: 'file-history-snapshot', isSnapshotUpdate: true }),
      JSON.stringify({
        type: 'user',
        cwd,
        timestamp: '2026-04-09T08:32:28.907Z',
        message: { role: 'user', content: '你好，世界' },
      }),
    ].join('\n');
    await fs.writeFile(filePath, `${jsonl}\n`, 'utf-8');

    const scanner = new ClaudeSessionScanner();
    const projects = await scanner.scanProjects();

    expect(projects).toHaveLength(1);
    expect(projects[0]?.id).toBe(projectId);
    expect(projects[0]?.path).toBe(cwd);
  });

  it('extracts firstMessage when message.content is a string', async () => {
    const projectId = 'D--Projects-jyw-ai-jyw-ai-client';
    const projectDir = path.join(tempDir, 'projects', projectId);
    await fs.mkdir(projectDir, { recursive: true });

    const filePath = path.join(projectDir, 'session-1.jsonl');
    const jsonl = [
      JSON.stringify({
        type: 'user',
        cwd: 'D:\\Projects\\jyw_ai\\jyw-ai-client',
        timestamp: '2026-04-09T08:32:28.907Z',
        message: { role: 'user', content: '第一行\n第二行' },
      }),
    ].join('\n');
    await fs.writeFile(filePath, `${jsonl}\n`, 'utf-8');

    const scanner = new ClaudeSessionScanner();
    const sessions = await scanner.getSessionsForProject(projectId);

    expect(sessions).toHaveLength(1);
    expect(sessions[0]?.firstMessage).toBe('第一行 第二行');
  });

  it('strips system tags from firstMessage preview', async () => {
    const projectId = 'D--Projects-jyw-ai-jyw-ai-client';
    const projectDir = path.join(tempDir, 'projects', projectId);
    await fs.mkdir(projectDir, { recursive: true });

    const filePath = path.join(projectDir, 'session-sys.jsonl');
    const jsonl = [
      JSON.stringify({
        type: 'user',
        cwd: 'D:\\Projects\\jyw_ai\\jyw-ai-client',
        timestamp: '2026-04-09T08:00:00.000Z',
        message: {
          role: 'user',
          content:
            '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>\n' +
            '<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>\n<local-command-stdout></local-command-stdout>\n' +
            '修复历史会话预览问题',
        },
      }),
    ].join('\n');
    await fs.writeFile(filePath, `${jsonl}\n`, 'utf-8');

    const scanner = new ClaudeSessionScanner();
    const sessions = await scanner.getSessionsForProject(projectId);

    expect(sessions).toHaveLength(1);
    expect(sessions[0]?.firstMessage).toBe('修复历史会话预览问题');
  });

  it('uses command name fallback when message is purely system tags', async () => {
    const projectId = 'D--Projects-jyw-ai-jyw-ai-client';
    const projectDir = path.join(tempDir, 'projects', projectId);
    await fs.mkdir(projectDir, { recursive: true });

    const filePath = path.join(projectDir, 'session-cmd.jsonl');
    const jsonl = [
      JSON.stringify({
        type: 'user',
        cwd: 'D:\\Projects\\jyw_ai\\jyw-ai-client',
        timestamp: '2026-04-09T08:00:00.000Z',
        message: {
          role: 'user',
          content:
            '<command-message>opsx:propose</command-message>  <command-name>/opsx:propose</command-name>\n<command-args></command-args>',
        },
      }),
    ].join('\n');
    await fs.writeFile(filePath, `${jsonl}\n`, 'utf-8');

    const scanner = new ClaudeSessionScanner();
    const sessions = await scanner.getSessionsForProject(projectId);

    expect(sessions).toHaveLength(1);
    expect(sessions[0]?.firstMessage).toBe('/opsx:propose');
  });

  it('skips system-only messages and finds real user message', async () => {
    const projectId = 'D--Projects-jyw-ai-jyw-ai-client';
    const projectDir = path.join(tempDir, 'projects', projectId);
    await fs.mkdir(projectDir, { recursive: true });

    const filePath = path.join(projectDir, 'session-skip.jsonl');
    const jsonl = [
      JSON.stringify({
        type: 'user',
        cwd: 'D:\\Projects\\jyw_ai\\jyw-ai-client',
        timestamp: '2026-04-09T08:00:00.000Z',
        message: {
          role: 'user',
          content:
            '<local-command-caveat>Caveat: system text.</local-command-caveat>\n<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>\n<local-command-stdout></local-command-stdout>',
        },
      }),
      JSON.stringify({
        type: 'assistant',
        timestamp: '2026-04-09T08:00:01.000Z',
        message: { role: 'assistant', content: 'OK' },
      }),
      JSON.stringify({
        type: 'user',
        timestamp: '2026-04-09T08:00:02.000Z',
        message: { role: 'user', content: '帮我优化这段代码' },
      }),
    ].join('\n');
    await fs.writeFile(filePath, `${jsonl}\n`, 'utf-8');

    const scanner = new ClaudeSessionScanner();
    const sessions = await scanner.getSessionsForProject(projectId);

    expect(sessions).toHaveLength(1);
    expect(sessions[0]?.firstMessage).toBe('帮我优化这段代码');
  });

  it('extracts firstMessage when message.content is an array of blocks', async () => {
    const projectId = 'D--Projects-jyw-ai-jyw-ai-client';
    const projectDir = path.join(tempDir, 'projects', projectId);
    await fs.mkdir(projectDir, { recursive: true });

    const filePath = path.join(projectDir, 'session-2.jsonl');
    const jsonl = [
      JSON.stringify({
        type: 'user',
        cwd: 'D:\\Projects\\jyw_ai\\jyw-ai-client',
        timestamp: '2026-04-09T08:32:28.907Z',
        message: {
          role: 'user',
          content: [
            { type: 'text', text: 'Hello' },
            { type: 'text', text: 'World' },
            { type: 'tool_result', content: 'ignored' },
          ],
        },
      }),
    ].join('\n');
    await fs.writeFile(filePath, `${jsonl}\n`, 'utf-8');

    const scanner = new ClaudeSessionScanner();
    const sessions = await scanner.getSessionsForProject(projectId);

    expect(sessions).toHaveLength(1);
    expect(sessions[0]?.firstMessage).toBe('Hello World');
  });
});

