import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { app } from 'electron';
import { writeSettingsFile } from '../auth/managedFileWriter';

interface StatusLineConfig {
  type: 'command' | 'text';
  command?: string;
  text?: string;
  padding?: number;
}

interface ClaudeSettings {
  hooks?: {
    Stop?: Array<{
      matcher?: string;
      hooks: Array<{
        type: 'command' | 'prompt';
        command?: string;
        prompt?: string;
        timeout?: number;
      }>;
    }>;
    PermissionRequest?: Array<{
      matcher?: string;
      hooks: Array<{
        type: 'command' | 'prompt';
        command?: string;
        prompt?: string;
        timeout?: number;
      }>;
    }>;
    PreToolUse?: Array<{
      matcher?: string;
      hooks: Array<{
        type: 'command' | 'prompt';
        command?: string;
        prompt?: string;
        timeout?: number;
      }>;
    }>;
    UserPromptSubmit?: Array<{
      matcher?: string;
      hooks: Array<{
        type: 'command' | 'prompt';
        command?: string;
        prompt?: string;
        timeout?: number;
      }>;
    }>;
    [key: string]: unknown;
  };
  statusLine?: StatusLineConfig;
  [key: string]: unknown;
}

interface StatusLineBackup {
  originalConfig: StatusLineConfig | null;
  backupTime: string;
}

// Hook is identified by the script path 'aiclient-hook' in the command
// Use .cjs extension to force CommonJS mode regardless of user's package.json "type" setting
const HOOK_SCRIPT_NAME = 'aiclient-hook.cjs';
const HOOK_MARKER = 'aiclient-hook';

// Legacy script name for migration
const LEGACY_SCRIPT_NAME = 'aiclient-stop.cjs';
const LEGACY_MARKER = 'aiclient-stop';

function getClaudeConfigDir(): string {
  if (process.env.CLAUDE_CONFIG_DIR) {
    return process.env.CLAUDE_CONFIG_DIR;
  }
  return path.join(os.homedir(), '.claude');
}

function getClaudeSettingsPath(): string {
  return path.join(getClaudeConfigDir(), 'settings.json');
}

/**
 * Env snapshot extraction (D47 S2 §1): derived directly from the in-memory
 * settings object a managedFileWriter mutator is handed (the freshest
 * on-disk content for this queue turn) instead of a separate `readFileSync`
 * right before writing — same information, one fewer TOCTOU-prone read.
 */
function extractEnvSnapshot(settings: ClaudeSettings): { baseUrl: string; authToken: string } {
  const env = (settings.env as Record<string, unknown> | undefined) ?? {};
  return {
    baseUrl: typeof env.ANTHROPIC_BASE_URL === 'string' ? env.ANTHROPIC_BASE_URL : '',
    authToken: typeof env.ANTHROPIC_AUTH_TOKEN === 'string' ? env.ANTHROPIC_AUTH_TOKEN : '',
  };
}

/**
 * Assertion-only guard (D47 S2 §1): the actual write now goes through
 * `managedFileWriter.writeSettingsFile`'s queued read-modify-write, so this
 * function no longer writes anything — it only compares the env captured
 * before a hook mutation to the env baked into the settings the mutator is
 * about to return, and loudly warns if we're about to drop the user's
 * Anthropic credentials. Warning semantics are unchanged from pre-S2: we log
 * instead of refusing because settings.json may legitimately have empty env
 * (logout, pre-onboarding) — refusing would break those flows. The signal we
 * want is "env was there and we lost it".
 */
function warnIfEnvRegressed(
  before: { baseUrl: string; authToken: string },
  next: ClaudeSettings,
  callerName: string
): void {
  if (!before.baseUrl && !before.authToken) return;
  const after = extractEnvSnapshot(next);
  if (after.baseUrl !== before.baseUrl || after.authToken !== before.authToken) {
    console.error(
      `[ClaudeHookManager] ENV REGRESSION in ${callerName}: settings.env Anthropic keys changed during a hook write. ` +
        `before(baseUrl=${before.baseUrl ? 'set' : 'empty'}, token=${before.authToken ? 'set' : 'empty'}) ` +
        `after(baseUrl=${after.baseUrl ? 'set' : 'empty'}, token=${after.authToken ? 'set' : 'empty'}) ` +
        `topKeys=${Object.keys(next as object).join(',')}`
    );
  }
}

function getHooksDir(): string {
  return path.join(getClaudeConfigDir(), 'hooks');
}

function getHookScriptPath(): string {
  return path.join(getHooksDir(), HOOK_SCRIPT_NAME);
}

function getLegacyHookScriptPath(): string {
  return path.join(getHooksDir(), LEGACY_SCRIPT_NAME);
}

/**
 * Node.js hook script content - runs on all platforms
 * Handles: Stop, PermissionRequest (AskUserQuestion), UserPromptSubmit
 */
function getHookScriptContent(): string {
  const ideDir = path.join(getClaudeConfigDir(), 'ide');
  // Use forward slashes for path in JS (works on all platforms)
  const ideDirJs = ideDir.replace(/\\/g, '/');

  return `// AiClient Hook - Sends agent notifications
// Auto-generated by AiClient - Do not edit manually
// Requires Node.js in PATH
// Handles: Stop, PermissionRequest (AskUserQuestion), UserPromptSubmit

const fs = require('fs');
const path = require('path');
const http = require('http');

const IDE_DIR = '${ideDirJs}';

function normalizePathForMatch(p) {
  if (typeof p !== 'string' || p.length === 0) return '';
  let normalized = p.replace(/\\\\/g, '/').replace(/\\/+$/, '');
  if (process.platform === 'win32' || process.platform === 'darwin') {
    normalized = normalized.toLowerCase();
  }
  return normalized;
}

function getPayloadCwd(data) {
  if (typeof data?.cwd === 'string') return data.cwd;
  if (typeof data?.workspace?.current_dir === 'string') return data.workspace.current_dir;
  if (typeof data?.workspace?.project_dir === 'string') return data.workspace.project_dir;
  if (typeof data?.project_dir === 'string') return data.project_dir;
  return undefined;
}

function getWorkspaceMatchScore(payloadCwd, workspaceFolders) {
  const normalizedCwd = normalizePathForMatch(payloadCwd);
  if (!normalizedCwd || !Array.isArray(workspaceFolders) || workspaceFolders.length === 0) {
    return -1;
  }

  let bestScore = -1;
  for (const folder of workspaceFolders) {
    const normalizedFolder = normalizePathForMatch(folder);
    if (!normalizedFolder) continue;

    // Match when cwd is inside workspace or workspace is inside cwd.
    if (
      normalizedCwd === normalizedFolder ||
      normalizedCwd.startsWith(normalizedFolder + '/') ||
      normalizedFolder.startsWith(normalizedCwd + '/')
    ) {
      bestScore = Math.max(bestScore, normalizedFolder.length);
    }
  }
  return bestScore;
}

function postAgentHook(port, postData) {
  return new Promise((resolve) => {
    const req = http.request(
      {
        hostname: '127.0.0.1',
        port,
        path: '/agent-hook',
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(postData),
        },
        timeout: 2000,
      },
      (res) => {
        res.resume();
        resolve(res.statusCode >= 200 && res.statusCode < 300);
      }
    );
    req.on('error', () => resolve(false));
    req.on('timeout', () => {
      req.destroy();
      resolve(false);
    });
    req.write(postData);
    req.end();
  });
}

async function main() {
  // Read JSON from stdin
  let input = '';
  process.stdin.setEncoding('utf8');
  for await (const chunk of process.stdin) {
    input += chunk;
  }

  let data;
  try {
    data = JSON.parse(input);
  } catch {
    process.exit(0);
  }

  const sessionId = data.session_id;
  if (!sessionId) {
    process.exit(0);
  }

  // Find AiClient lockfiles and send notification to the best matching workspace instance.
  // Fallback to other AiClient instances when matched lockfiles are stale.
  if (!fs.existsSync(IDE_DIR)) {
    process.exit(0);
  }

  const payloadCwd = getPayloadCwd(data);
  const lockfiles = fs.readdirSync(IDE_DIR).filter(f => f.endsWith('.lock'));
  const candidates = [];

  for (const lockfile of lockfiles) {
    try {
      const content = JSON.parse(fs.readFileSync(path.join(IDE_DIR, lockfile), 'utf-8'));
      if (content.ideName === 'AiClient') {
        const port = parseInt(path.basename(lockfile, '.lock'), 10);
        if (Number.isNaN(port)) continue;
        const score = getWorkspaceMatchScore(payloadCwd, content.workspaceFolders);
        candidates.push({ port, score });
      }
    } catch {
      // Ignore errors, try next lockfile
    }
  }

  if (candidates.length === 0) {
    process.exit(0);
  }

  // Prefer lockfiles whose workspaceFolders match payload cwd.
  // If no payload cwd or no match, keep previous resilience by trying all.
  const matched = candidates.filter(c => c.score >= 0).sort((a, b) => b.score - a.score);
  const fallback = candidates.filter(c => c.score < 0);
  const targets = matched.length > 0 ? [...matched, ...fallback] : fallback;

  const postData = JSON.stringify(data);
  for (const target of targets) {
    const ok = await postAgentHook(target.port, postData);
    if (ok) {
      break;
    }
  }
}

main().catch(() => process.exit(0));
`;
}

function ensureHookScript(): string {
  const hooksDir = getHooksDir();
  const scriptPath = getHookScriptPath();

  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true, mode: 0o755 });
  }

  // Migrate legacy script if exists
  const legacyScriptPath = getLegacyHookScriptPath();
  if (fs.existsSync(legacyScriptPath)) {
    try {
      fs.unlinkSync(legacyScriptPath);
      console.log('[ClaudeHookManager] Removed legacy script:', LEGACY_SCRIPT_NAME);
    } catch (err) {
      console.warn('[ClaudeHookManager] Failed to remove legacy script:', err);
    }
  }

  // TODO(v0.3.0): Remove legacy .js cleanup
  const legacyScriptPath2 = path.join(hooksDir, 'aiclient-stop.js');
  if (fs.existsSync(legacyScriptPath2)) {
    fs.unlinkSync(legacyScriptPath2);
  }

  fs.writeFileSync(scriptPath, getHookScriptContent(), { mode: 0o755 });

  return scriptPath;
}

/**
 * Generate hook command that runs the script using Node.js
 * Requires Node.js to be installed and available in PATH
 */
function generateHookCommand(): string {
  const scriptPath = getHookScriptPath();
  // Use forward slashes for cross-platform compatibility
  const scriptPathCmd = scriptPath.replace(/\\/g, '/');

  return `node "${scriptPathCmd}"`;
}

/**
 * Check if Claude CLI is installed by verifying .claude directory exists
 * This prevents creating config files for users who don't have Claude installed
 */
export function isClaudeInstalled(): boolean {
  const configDir = getClaudeConfigDir();
  return fs.existsSync(configDir);
}

/**
 * Ensure the Stop hook is configured in Claude settings
 * Returns true if hook was added or already exists
 * Returns false if Claude is not installed (skips setup)
 */
export async function ensureStopHook(): Promise<boolean> {
  // Skip hook setup if Claude is not installed
  if (!isClaudeInstalled()) {
    console.log('[ClaudeHookManager] Claude not installed, skipping hook setup');
    return false;
  }

  try {
    const settingsPath = getClaudeSettingsPath();
    const configDir = getClaudeConfigDir();
    if (!fs.existsSync(configDir)) {
      fs.mkdirSync(configDir, { recursive: true, mode: 0o700 });
    }

    // D47 S2 §1: legacy-reference migration + hook-presence check + hook
    // append all run inside managedFileWriter's per-path queue, against
    // whatever the freshest on-disk content is at this mutator's turn — not
    // a snapshot read before the queue. This is what keeps a concurrent
    // claudeHome generator write and this hook write from losing either
    // side's sentinel (spec §3-1). The settings write always lands before
    // `ensureHookScript()` runs below, preserving the pre-refactor ordering
    // guarantee ("migrate settings before deleting legacy script files").
    await writeSettingsFile(settingsPath, (current) => {
      const settings = current as ClaudeSettings;
      const before = extractEnvSnapshot(settings);

      // Remove old .js and legacy .cjs references.
      if (settings.hooks?.Stop) {
        settings.hooks.Stop = settings.hooks.Stop.filter(
          (hookGroup) =>
            !hookGroup.hooks?.some(
              (hook) =>
                hook.type === 'command' &&
                (hook.command?.includes('aiclient-stop.js') ||
                  hook.command?.includes(LEGACY_MARKER))
            )
        );
        if (settings.hooks.Stop.length === 0) {
          delete settings.hooks.Stop;
        }
      }

      // Check if already configured (with NEW hook marker only, not legacy)
      const hasCurrentHook = settings.hooks?.Stop?.some((hookGroup) =>
        hookGroup.hooks?.some(
          (hook) => hook.type === 'command' && hook.command?.includes(HOOK_MARKER)
        )
      );
      if (!hasCurrentHook) {
        if (!settings.hooks) {
          settings.hooks = {};
        }
        if (!settings.hooks.Stop) {
          settings.hooks.Stop = [];
        }
        // Add our hook - marker is embedded in the command for identification
        settings.hooks.Stop.push({
          matcher: '',
          hooks: [
            {
              type: 'command',
              // Marker is checked via includes(HOOK_MARKER), embedded in command itself
              command: generateHookCommand(),
              timeout: 5,
            },
          ],
        });
      }

      warnIfEnvRegressed(before, settings, 'ensureStopHook');
      return settings;
    });

    // Now safe to update script files (settings.json is already clean)
    ensureHookScript();

    console.log('[ClaudeHookManager] Stop hook configured successfully');
    return true;
  } catch (error) {
    console.error('[ClaudeHookManager] Failed to configure Stop hook:', error);
    return false;
  }
}

/**
 * Remove AiClient Stop hook from Claude settings
 */
export async function removeStopHook(): Promise<boolean> {
  try {
    const settingsPath = getClaudeSettingsPath();

    if (!fs.existsSync(settingsPath)) {
      return true;
    }

    await writeSettingsFile(settingsPath, (current) => {
      const settings = current as ClaudeSettings;
      if (!settings.hooks?.Stop) {
        return settings;
      }

      // Filter out our hook (both current and legacy)
      settings.hooks.Stop = settings.hooks.Stop.filter(
        (hookGroup) =>
          !hookGroup.hooks?.some(
            (hook) =>
              hook.type === 'command' &&
              (hook.command?.includes(HOOK_MARKER) ||
                hook.command?.includes(LEGACY_MARKER) ||
                hook.command?.includes('aiclient-stop'))
          )
      );

      // Clean up empty arrays
      if (settings.hooks.Stop.length === 0) {
        delete settings.hooks.Stop;
      }
      if (Object.keys(settings.hooks).length === 0) {
        delete settings.hooks;
      }

      return settings;
    });

    console.log('[ClaudeHookManager] Stop hook removed successfully');
    return true;
  } catch (error) {
    console.error('[ClaudeHookManager] Failed to remove Stop hook:', error);
    return false;
  }
}

// ============================================================================
// Status Line Hook Management
// ============================================================================

const STATUSLINE_SCRIPT_NAME = 'aiclient-statusline.cjs';
const STATUSLINE_BACKUP_FILE = 'claude-statusline-backup.json';

function getStatusLineScriptPath(): string {
  return path.join(getHooksDir(), STATUSLINE_SCRIPT_NAME);
}

function getStatusLineBackupPath(): string {
  return path.join(app.getPath('userData'), STATUSLINE_BACKUP_FILE);
}

/**
 * Generate status line script content
 */
function getStatusLineScriptContent(): string {
  const ideDir = path.join(getClaudeConfigDir(), 'ide');
  const ideDirJs = ideDir.replace(/\\/g, '/');

  return `// AiClient Status Line Hook - Forwards status data to AiClient
// Auto-generated by AiClient - Do not edit manually

const fs = require('fs');
const path = require('path');
const http = require('http');

const IDE_DIR = '${ideDirJs}';

async function main() {
  // Read JSON from stdin
  let input = '';
  process.stdin.setEncoding('utf8');
  for await (const chunk of process.stdin) {
    input += chunk;
  }

  let data;
  try {
    data = JSON.parse(input);
  } catch {
    // Output empty line if parsing fails
    console.log('');
    process.exit(0);
  }

  // Find AiClient lockfiles and send status update to ALL instances
  if (fs.existsSync(IDE_DIR)) {
    const lockfiles = fs.readdirSync(IDE_DIR).filter(f => f.endsWith('.lock'));
    for (const lockfile of lockfiles) {
      try {
        const content = JSON.parse(fs.readFileSync(path.join(IDE_DIR, lockfile), 'utf-8'));
        if (content.ideName === 'AiClient') {
          const port = path.basename(lockfile, '.lock');
          const postData = JSON.stringify(data);
          const req = http.request({
            hostname: '127.0.0.1',
            port: parseInt(port),
            path: '/status-line',
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'Content-Length': Buffer.byteLength(postData),
            },
            timeout: 1000,
          });
          req.on('error', () => {});
          req.write(postData);
          req.end();
          // Don't break - send to all AiClient instances
        }
      } catch {
        // Ignore errors, try next lockfile
      }
    }
  }

  // Output empty line - don't override Claude's native status line display
  console.log('');
}

main().catch(() => {
  console.log('');
  process.exit(0);
});
`;
}

function ensureStatusLineScript(): string {
  const hooksDir = getHooksDir();
  const scriptPath = getStatusLineScriptPath();

  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true, mode: 0o755 });
  }

  // TODO(v0.3.0): Remove legacy .js cleanup
  const legacyScriptPath = path.join(hooksDir, 'aiclient-statusline.js');
  if (fs.existsSync(legacyScriptPath)) {
    fs.unlinkSync(legacyScriptPath);
  }

  fs.writeFileSync(scriptPath, getStatusLineScriptContent(), { mode: 0o755 });
  return scriptPath;
}

/**
 * Generate status line command
 */
function generateStatusLineCommand(): string {
  const scriptPath = getStatusLineScriptPath();
  const scriptPathCmd = scriptPath.replace(/\\/g, '/');
  return `node "${scriptPathCmd}"`;
}

/**
 * Check if our status line hook is configured
 */
function isStatusLineHookConfigured(settings: ClaudeSettings): boolean {
  return (
    settings.statusLine?.type === 'command' &&
    (settings.statusLine?.command?.includes(STATUSLINE_SCRIPT_NAME) ?? false)
  );
}

/**
 * Backup existing status line config
 */
function backupStatusLineConfig(currentConfig: StatusLineConfig | undefined): void {
  const backupPath = getStatusLineBackupPath();

  // Don't backup if already backed up
  if (fs.existsSync(backupPath)) {
    return;
  }

  const backup: StatusLineBackup = {
    originalConfig: currentConfig ?? null,
    backupTime: new Date().toISOString(),
  };

  const userDataDir = app.getPath('userData');
  if (!fs.existsSync(userDataDir)) {
    fs.mkdirSync(userDataDir, { recursive: true });
  }

  fs.writeFileSync(backupPath, JSON.stringify(backup, null, 2), { mode: 0o600 });
  console.log('[ClaudeHookManager] Status line config backed up');
}

/**
 * Restore status line config from backup
 */
function restoreStatusLineConfig(): StatusLineConfig | null | undefined {
  const backupPath = getStatusLineBackupPath();

  if (!fs.existsSync(backupPath)) {
    return undefined; // No backup exists
  }

  try {
    const content = fs.readFileSync(backupPath, 'utf-8');
    const backup: StatusLineBackup = JSON.parse(content);

    // Delete backup file after reading
    fs.unlinkSync(backupPath);

    console.log('[ClaudeHookManager] Status line config restored from backup');
    return backup.originalConfig;
  } catch (error) {
    console.error('[ClaudeHookManager] Failed to restore status line backup:', error);
    return undefined;
  }
}

/**
 * Ensure status line hook is configured
 */
export async function ensureStatusLineHook(): Promise<boolean> {
  if (!isClaudeInstalled()) {
    console.log('[ClaudeHookManager] Claude not installed, skipping status line hook setup');
    return false;
  }

  try {
    // Ensure script file is up-to-date
    ensureStatusLineScript();

    const settingsPath = getClaudeSettingsPath();
    const configDir = getClaudeConfigDir();
    if (!fs.existsSync(configDir)) {
      fs.mkdirSync(configDir, { recursive: true, mode: 0o700 });
    }

    // D47 S2 §1: legacy cleanup + already-configured check + backup + new
    // statusLine assignment all run inside one managedFileWriter mutator
    // turn, against the freshest on-disk content (see `ensureStopHook`).
    await writeSettingsFile(settingsPath, (current) => {
      const settings = current as ClaudeSettings;
      const before = extractEnvSnapshot(settings);

      // TODO(v0.3.0): Remove legacy .js cleanup from settings.json
      // Clean up legacy .js reference in statusLine (file may have been deleted in previous versions)
      if (
        settings.statusLine?.type === 'command' &&
        settings.statusLine?.command?.includes('aiclient-statusline.js')
      ) {
        console.log('[ClaudeHookManager] Cleaned up legacy .js statusLine reference from settings');
        delete settings.statusLine;
      }

      // Already configured
      if (isStatusLineHookConfigured(settings)) {
        return settings;
      }

      // Backup existing config
      backupStatusLineConfig(settings.statusLine);

      // Set our status line config
      settings.statusLine = {
        type: 'command',
        command: generateStatusLineCommand(),
        padding: 0,
      };

      warnIfEnvRegressed(before, settings, 'ensureStatusLineHook');
      return settings;
    });

    console.log('[ClaudeHookManager] Status line hook configured successfully');
    return true;
  } catch (error) {
    console.error('[ClaudeHookManager] Failed to configure status line hook:', error);
    return false;
  }
}

/**
 * Remove status line hook and restore original config
 */
export async function removeStatusLineHook(): Promise<boolean> {
  try {
    const settingsPath = getClaudeSettingsPath();

    if (!fs.existsSync(settingsPath)) {
      return true;
    }

    let removed = false;
    await writeSettingsFile(settingsPath, (current) => {
      const settings = current as ClaudeSettings;

      // Only remove if it's our hook
      if (!isStatusLineHookConfigured(settings)) {
        return settings;
      }
      removed = true;

      // Restore from backup
      const originalConfig = restoreStatusLineConfig();

      if (originalConfig === undefined || originalConfig === null) {
        // No backup, or original had no config — just delete our config
        delete settings.statusLine;
      } else {
        // Restore original config
        settings.statusLine = originalConfig;
      }

      return settings;
    });

    if (removed) {
      // Remove script file
      const scriptPath = getStatusLineScriptPath();
      if (fs.existsSync(scriptPath)) {
        fs.unlinkSync(scriptPath);
      }
      console.log('[ClaudeHookManager] Status line hook removed successfully');
    }
    return true;
  } catch (error) {
    console.error('[ClaudeHookManager] Failed to remove status line hook:', error);
    return false;
  }
}

/**
 * Check if status line hook is installed
 */
export function isStatusLineHookInstalled(): boolean {
  try {
    const settingsPath = getClaudeSettingsPath();
    if (!fs.existsSync(settingsPath)) {
      return false;
    }

    const content = fs.readFileSync(settingsPath, 'utf-8');
    const settings: ClaudeSettings = JSON.parse(content);
    return isStatusLineHookConfigured(settings);
  } catch {
    return false;
  }
}

// ============================================================================
// PermissionRequest Hook Management (for AskUserQuestion notifications)
// ============================================================================

/**
 * Check if PermissionRequest hook is configured
 */
function isPermissionRequestHookConfigured(settings: ClaudeSettings): boolean {
  if (!settings.hooks?.PermissionRequest) {
    return false;
  }

  return settings.hooks.PermissionRequest.some((hookGroup) =>
    hookGroup.hooks?.some(
      (hook) =>
        hook.type === 'command' &&
        (hook.command?.includes(HOOK_MARKER) || hook.command?.includes(LEGACY_MARKER))
    )
  );
}

/**
 * Ensure PermissionRequest hook is configured
 */
export async function ensurePermissionRequestHook(): Promise<boolean> {
  if (!isClaudeInstalled()) {
    console.log('[ClaudeHookManager] Claude not installed, skipping PermissionRequest hook setup');
    return false;
  }

  try {
    const settingsPath = getClaudeSettingsPath();
    const configDir = getClaudeConfigDir();
    if (!fs.existsSync(configDir)) {
      fs.mkdirSync(configDir, { recursive: true, mode: 0o700 });
    }

    // D47 S2 §1: migration + hasCurrentHook check + hook append merged into
    // one managedFileWriter mutator turn (see `ensureStopHook` for rationale).
    await writeSettingsFile(settingsPath, (current) => {
      const settings = current as ClaudeSettings;
      const before = extractEnvSnapshot(settings);

      // Migrate legacy hook references (aiclient-stop -> aiclient-hook)
      if (settings.hooks?.PermissionRequest) {
        settings.hooks.PermissionRequest = settings.hooks.PermissionRequest.filter(
          (hookGroup) =>
            !hookGroup.hooks?.some(
              (hook) =>
                hook.type === 'command' &&
                (hook.command?.includes('aiclient-stop.js') ||
                  hook.command?.includes(LEGACY_MARKER))
            )
        );
        if (settings.hooks.PermissionRequest.length === 0) {
          delete settings.hooks.PermissionRequest;
        }
      }

      // Check if already configured (with NEW hook marker only)
      const hasCurrentHook = settings.hooks?.PermissionRequest?.some((hookGroup) =>
        hookGroup.hooks?.some(
          (hook) => hook.type === 'command' && hook.command?.includes(HOOK_MARKER)
        )
      );
      if (!hasCurrentHook) {
        if (!settings.hooks) {
          settings.hooks = {};
        }
        if (!settings.hooks.PermissionRequest) {
          settings.hooks.PermissionRequest = [];
        }
        // Add our hook - reuse the same aiclient-hook.cjs script
        settings.hooks.PermissionRequest.push({
          matcher: '',
          hooks: [
            {
              type: 'command',
              command: generateHookCommand(),
              timeout: 5,
            },
          ],
        });
      }

      warnIfEnvRegressed(before, settings, 'ensurePermissionRequestHook');
      return settings;
    });

    console.log('[ClaudeHookManager] PermissionRequest hook configured successfully');
    return true;
  } catch (error) {
    console.error('[ClaudeHookManager] Failed to configure PermissionRequest hook:', error);
    return false;
  }
}

/**
 * Ensure UserPromptSubmit hook is configured in Claude settings
 * This hook triggers when user submits a message to Claude
 */
export async function ensureUserPromptSubmitHook(): Promise<boolean> {
  if (!isClaudeInstalled()) {
    console.log('[ClaudeHookManager] Claude not installed, skipping UserPromptSubmit hook setup');
    return false;
  }

  try {
    const settingsPath = getClaudeSettingsPath();
    const configDir = getClaudeConfigDir();
    if (!fs.existsSync(configDir)) {
      fs.mkdirSync(configDir, { recursive: true, mode: 0o700 });
    }

    // D47 S2 §1: hasCurrentHook check + hook append merged into one
    // managedFileWriter mutator turn (see `ensureStopHook` for rationale).
    await writeSettingsFile(settingsPath, (current) => {
      const settings = current as ClaudeSettings;
      const before = extractEnvSnapshot(settings);

      // Check if already configured
      const hasCurrentHook = settings.hooks?.UserPromptSubmit?.some((hookGroup) =>
        hookGroup.hooks?.some(
          (hook) => hook.type === 'command' && hook.command?.includes(HOOK_MARKER)
        )
      );
      if (!hasCurrentHook) {
        if (!settings.hooks) {
          settings.hooks = {};
        }
        if (!settings.hooks.UserPromptSubmit) {
          settings.hooks.UserPromptSubmit = [];
        }
        // Add our hook - reuse the same aiclient-hook.cjs script
        settings.hooks.UserPromptSubmit.push({
          matcher: '',
          hooks: [
            {
              type: 'command',
              command: generateHookCommand(),
              timeout: 5,
            },
          ],
        });
      }

      warnIfEnvRegressed(before, settings, 'ensureUserPromptSubmitHook');
      return settings;
    });

    console.log('[ClaudeHookManager] UserPromptSubmit hook configured successfully');
    return true;
  } catch (error) {
    console.error('[ClaudeHookManager] Failed to configure UserPromptSubmit hook:', error);
    return false;
  }
}

/**
 * Ensure PreToolUse hook is configured in Claude settings
 * This hook triggers when Claude starts using any tool
 */
export async function ensurePreToolUseHook(): Promise<boolean> {
  if (!isClaudeInstalled()) {
    console.log('[ClaudeHookManager] Claude not installed, skipping PreToolUse hook setup');
    return false;
  }

  try {
    const settingsPath = getClaudeSettingsPath();
    const configDir = getClaudeConfigDir();
    if (!fs.existsSync(configDir)) {
      fs.mkdirSync(configDir, { recursive: true, mode: 0o700 });
    }

    // D47 S2 §1: hasCurrentHook check + hook append merged into one
    // managedFileWriter mutator turn (see `ensureStopHook` for rationale).
    await writeSettingsFile(settingsPath, (current) => {
      const settings = current as ClaudeSettings;
      const before = extractEnvSnapshot(settings);

      // Check if already configured
      const hasCurrentHook = settings.hooks?.PreToolUse?.some((hookGroup) =>
        hookGroup.hooks?.some(
          (hook) => hook.type === 'command' && hook.command?.includes(HOOK_MARKER)
        )
      );
      if (!hasCurrentHook) {
        if (!settings.hooks) {
          settings.hooks = {};
        }
        if (!settings.hooks.PreToolUse) {
          settings.hooks.PreToolUse = [];
        }
        // Add our hook - reuse the same aiclient-hook.cjs script
        settings.hooks.PreToolUse.push({
          matcher: '',
          hooks: [
            {
              type: 'command',
              command: generateHookCommand(),
              timeout: 5,
            },
          ],
        });
      }

      warnIfEnvRegressed(before, settings, 'ensurePreToolUseHook');
      return settings;
    });

    console.log('[ClaudeHookManager] PreToolUse hook configured successfully');
    return true;
  } catch (error) {
    console.error('[ClaudeHookManager] Failed to configure PreToolUse hook:', error);
    return false;
  }
}

/**
 * Remove PermissionRequest hook from Claude settings
 */
export async function removePermissionRequestHook(): Promise<boolean> {
  try {
    const settingsPath = getClaudeSettingsPath();

    if (!fs.existsSync(settingsPath)) {
      return true;
    }

    await writeSettingsFile(settingsPath, (current) => {
      const settings = current as ClaudeSettings;
      if (!settings.hooks?.PermissionRequest) {
        return settings;
      }

      // Filter out our hook (both current and legacy)
      settings.hooks.PermissionRequest = settings.hooks.PermissionRequest.filter(
        (hookGroup) =>
          !hookGroup.hooks?.some(
            (hook) =>
              hook.type === 'command' &&
              (hook.command?.includes(HOOK_MARKER) || hook.command?.includes(LEGACY_MARKER))
          )
      );

      // Clean up empty PermissionRequest array
      if (settings.hooks.PermissionRequest.length === 0) {
        delete settings.hooks.PermissionRequest;
      }

      // Clean up empty hooks object
      if (Object.keys(settings.hooks).length === 0) {
        delete settings.hooks;
      }

      return settings;
    });

    console.log('[ClaudeHookManager] PermissionRequest hook removed successfully');
    return true;
  } catch (error) {
    console.error('[ClaudeHookManager] Failed to remove PermissionRequest hook:', error);
    return false;
  }
}

/**
 * Check if PermissionRequest hook is installed
 */
export function isPermissionRequestHookInstalled(): boolean {
  try {
    const settingsPath = getClaudeSettingsPath();
    if (!fs.existsSync(settingsPath)) {
      return false;
    }

    const content = fs.readFileSync(settingsPath, 'utf-8');
    const settings: ClaudeSettings = JSON.parse(content);
    return isPermissionRequestHookConfigured(settings);
  } catch {
    return false;
  }
}
