import {
  composerSendingLine,
  type SendPhase,
  SLOW_WAIT_HINT_SECONDS,
  STALLED_HINT_SECONDS,
} from './attachments';

/**
 * T-31 turn-head status (reply-anatomy spec §3 / §4.7).
 *
 * The waiting copy this produces is NOT new: it is generated by
 * `attachments.ts`'s `composerSendingLine`, which `attachments.test.ts` already
 * pins word for word. Copying those strings here would put the same literal in
 * two places and hand the next edit a silent drift; instead this module calls
 * that function and only classifies the result. F-B5 asserts the delegation by
 * comparing this module's output against a same-argument
 * `composerSendingLine` call rather than against a literal.
 *
 * `kind` mirrors which branch of `composerSendingLine` actually produced the
 * text (handshake / stalled / slow / retry / plain awaiting), so the colour and
 * spinner the `.tsx` layer picks can never contradict the words on screen.
 *
 * Input is a plain object on purpose — no store import, so the whole six-state
 * table is assertable in vitest's node environment.
 */

export type TurnStatusKind =
  | 'handshake'
  | 'awaiting'
  | 'streaming'
  | 'slow'
  /**
   * F456 §7.5: the deeper of the two waiting tiers. Split off from `slow`
   * because `slow` stopped being remarkable once F2 raised the ceiling to
   * ~300s — a tier that is on for minutes cannot also be the alarm.
   */
  | 'stalled'
  | 'retrying'
  | 'failed';

export interface TurnStatus {
  kind: TurnStatusKind;
  text: string;
}

/**
 * Failed turn head label. Short and fixed-length by contract: the full error
 * text belongs to the session-level failure block, whose position §9-ζ keeps
 * unchanged, and `middleColumnLayout.ts`'s own status-line ruling already
 * states that any inline error status "must be a short, fixed-length label
 * (e.g. 'Failed'), never the full message".
 */
export const TURN_FAILED_TEXT = 'Failed';

export interface TurnStatusInput {
  /** The turn is in flight. A completed turn passes `false` and gets `null` (the `Worked for Ns` row takes the slot). */
  active: boolean;
  /** Send phase of the in-flight turn; only read while `active`. */
  phase: SendPhase;
  elapsedSeconds: number;
  /**
   * Reply budget in ms, passed straight through. F456 §7.2 retired the
   * `(up to Ns)` clause it used to print, so nothing downstream reads it —
   * see `composerSendingLine`'s own note on why the parameter stays.
   */
  budgetMs: number;
  attachmentCount: number;
  attachmentBytes: number;
  /**
   * F456 §7.4: size of this turn's prompt in code points, from the composer's
   * send snapshot. Optional because the fallback for "a session was already
   * running when this window opened" is no count at all, not a zero the line
   * would print as fact.
   */
  promptChars?: number;
  /** The CLI's transport-retry loop for this turn, if any. */
  retry?: { attempt: number; maxRetries: number } | null;
  /** The turn already produced at least one block, i.e. tokens are arriving. */
  hasBlocks?: boolean;
  /** The turn ended in failure. */
  failed?: boolean;
}

/**
 * Turn-head status (§4.7). Returns `null` for a completed turn — the head is a
 * single slot with two states, and `formatWorkedForRow` already returns `null`
 * until `latencyMs` exists, so the two never need mutual-exclusion logic.
 *
 * Branch order and why:
 *  1. `failed` — a failed turn is not in flight, so it is decided first.
 *  2. not `active` — complete, no status row at all.
 *  3. `handshake` — nothing has been transmitted yet, so no block can exist.
 *  4. `hasBlocks` — once tokens are arriving, "Waiting for … reply" / "Still
 *     waiting" are factually false, so `streaming` outranks both. §4.7 defines
 *     `awaiting` as "no block yet" for exactly this reason.
 *  5. the two waiting tiers (`stalled` >= `STALLED_HINT_SECONDS`, then `slow`
 *     >= `SLOW_WAIT_HINT_SECONDS`) before retry: at either point
 *     `composerSendingLine` itself switches to a "Still waiting …" wording
 *     (retry counter included as a suffix), and `kind` follows the copy branch
 *     that actually ran. Deeper tier first — the two overlap, and the more
 *     specific statement is the true one.
 */
export function deriveTurnStatus(input: TurnStatusInput): TurnStatus | null {
  if (input.failed) return { kind: 'failed', text: TURN_FAILED_TEXT };
  if (!input.active) return null;

  const elapsed = normalizeElapsedSeconds(input.elapsedSeconds);
  const text = composerSendingLine({
    phase: input.phase,
    elapsedSeconds: input.elapsedSeconds,
    budgetMs: input.budgetMs,
    attachmentCount: input.attachmentCount,
    attachmentBytes: input.attachmentBytes,
    retry: input.retry,
    // F456 §7.4: forwarded, not consumed here.
    promptChars: input.promptChars,
  });

  if (input.phase === 'handshake') return { kind: 'handshake', text };
  if (input.hasBlocks) {
    // No verb, no `✽` here on purpose (spec §3a): this module stays text-only
    // (see the file header's copy/decoration split) — the glyph is the `.tsx`
    // layer's prefix (`TurnStatusContent`, `MessageTimeline.tsx`), added only
    // once `kind === 'streaming'` reaches render.
    return { kind: 'streaming', text: formatElapsedClock(elapsed) };
  }

  // Both thresholds are imported, never re-declared, and tested in the SAME
  // ORDER `composerSendingLine` tests them: it keys its own wording switch off
  // the same two constants, so a `kind` can only ever name the sentence that
  // actually ran. F456 §7.5-a strengthened the invariant rather than weakening
  // it — one constant against one wording switch became two against two, still
  // unable to flip apart. Adding a tier here without a matching tier there (or
  // in the other order) is the failure this arrangement makes impossible.
  if (elapsed >= STALLED_HINT_SECONDS) return { kind: 'stalled', text };
  if (elapsed >= SLOW_WAIT_HINT_SECONDS) return { kind: 'slow', text };
  if (input.retry) return { kind: 'retrying', text };
  return { kind: 'awaiting', text };
}

/** Same normalization `composerSendingLine` applies, so both lines count the same second. */
function normalizeElapsedSeconds(elapsedSeconds: number): number {
  return Math.max(0, Math.floor(elapsedSeconds));
}

/**
 * D33: `42s` / `19m 55s` — the streaming branch's own clock format,
 * deliberately NOT `composerSendingLine`'s `Ns` wording. That format is
 * exempt from this split by design: its own window closes at
 * `SLOW_WAIT_HINT_SECONDS` (well under a minute), so a bare seconds count
 * never gets hard to read there. The streaming branch has no such ceiling —
 * a turn can run for several minutes — and a raw `"143s"` is materially
 * harder to scan at a glance than `"2m 23s"`.
 */
export function formatElapsedClock(elapsedSeconds: number): string {
  const totalSeconds = Math.max(0, Math.floor(elapsedSeconds));
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  return minutes > 0 ? `${minutes}m ${seconds}s` : `${seconds}s`;
}

/**
 * Round-10 inspection ③: when a turn fails, TWO renditions of the same error
 * can reach the timeline at once — the session-level "Session failed" card
 * (fed by the store's `lastError`) and an error-role notice message (appended
 * by the red-line store when the send promise rejects with the same failure).
 * The card is the richer surface (retry hint, Stop affordance), so when the
 * LATEST error notice already carries the text, the card drops its duplicate
 * body and keeps title/hint/actions. Containment (either direction) rather
 * than equality: the notice's text is typically `String(err)` — the same
 * message wearing an `Error: ` prefix.
 *
 * Pure and store-free; the failed-card-without-notice path (e.g. a replayed
 * failed session whose notice was never persisted) keeps its body.
 */
export function isFailedCardBodyDuplicate(
  lastError: string | null | undefined,
  latestNoticeText: string | null | undefined
): boolean {
  if (!lastError || !latestNoticeText) return false;
  return latestNoticeText.includes(lastError) || lastError.includes(latestNoticeText);
}

/** The most recent error-role notice's text, or null when none exists. */
export function latestErrorNoticeText(
  messages: readonly { role: string; blocks: readonly { type: string; text?: string }[] }[]
): string | null {
  for (let index = messages.length - 1; index >= 0; index -= 1) {
    const message = messages[index];
    if (message.role !== 'error') continue;
    const text = message.blocks
      .map((block) => (block.type === 'text' ? (block.text ?? '') : ''))
      .join('');
    return text.length > 0 ? text : null;
  }
  return null;
}
